get:
  summary: 'Get application by ID'
  operationId: getApplication
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Application Main Calls
  responses:
    '200':
      description: 'Get application by ID'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
put:
  summary: 'Edit application'
  description: |
    - To edit the application you must have the admin permission.
    - For port edition, if you provide a port id, we will update the corresponding port. If you don't we will create a new one. If you remove a port from the payload, we will delete it.
    - For storage edition, if you provide a storage id, we will update the corresponding storage. If you don't we will create a new one. If you remove a storage from the payload, we will delete it.
  operationId: editApplication
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Application Main Calls
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/ApplicationEditRequest.yaml'
  responses:
    '200':
      description: 'Edit application'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
    '409':
      description: Application name within the environment is already taken
delete:
  summary: 'Delete application'
  description: 'To delete the application you must have the admin permission'
  operationId: deleteApplication
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Application Main Calls
  responses:
    '204':
      $ref: '../responses/Deleted.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
