post:
  summary: 'Import secrets'
  description: Import secrets in a defined scope, with a defined visibility.
  operationId: importSecrets
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Application Environment Variable 
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/SecretImportRequest.yaml'
  responses:
    '201':
      description: 'Updated Environment Variable list'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentVariableResponseList.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
