get:
  summary: 'List application secrets'
  description: Secrets are like environment variables, but they are secured and can't be revealed.
  operationId: listApplicationSecrets
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Application Secret
  responses:
    '200':
      description: 'List secrets'
      content:
        application/json:
          schema:
            $ref: '../schemas/SecretResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
post:
  summary: 'Add a secret to the application'
  description: |
    - Add a secret to the application.
  operationId: createApplicationSecret
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'

  tags:
    - Application Secret
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/SecretRequest.yaml'
  responses:
    '201':
      description: 'Add a secret'
      content:
        application/json:
          schema:
            $ref: '../schemas/SecretResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
