post:
  summary: 'Link a database to the application'
  operationId: attachApplicationToDatabase
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/path/targetDatabaseId.yaml'
  tags:
    - application
  responses:
    '201':
      description: 'Linked the database to the application'
      content:
        application/json:
          schema:
            $ref: '../schemas/DatabaseResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '409':
      description: This database is already linked to the application

      
delete:
  summary: 'Remove database link to this application.'
  operationId: removeDatabaseFromApplication
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/path/targetDatabaseId.yaml'
  tags:
    - application
  responses:
    '204':
      $ref: '../responses/NoContent.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
