get:
  summary: 'Get Health Check latency  metric over time for the application'
  description: 'The value returned corresponds to the 95th centile'
  operationId: getApplicationMetricHealthCheck
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/query/lastSeconds.yaml'
  tags:
    - Application Metrics
  responses:
    '200':
      description: 'Health Check Latency'
      content:
        application/json:
          schema:
            $ref: '../schemas/MetricGenericResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
