get:
  summary: 'List last commits'
  description: Returns list of the last 100 commits made on the repository linked to the application

  operationId: listApplicationCommit
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/query/startId.yaml'
    - $ref: '../parameters/query/gitCommitId.yaml'

  tags:
    - Application Main Calls
  responses:
    '200':
      description: 'List commits'
      content:
        application/json:
          schema:
            $ref: '../schemas/CommitResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
