get:
  summary: 'List linked databases'
  operationId: listApplicationDatabase
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - application
  responses:
    '200':
      description: 'List linked databases'
      content:
        application/json:
          schema:
            $ref: '../schemas/AttachApplicationToDatabaseResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
post:
  summary: 'Link the application to a database'
  operationId: attachApplicationToDatabase
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - application
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/AttachApplicationToDatabaseRequest.yaml'
  responses:
    '201':
      description: 'Link the application to a database'
      content:
        application/json:
          schema:
            $ref: '../schemas/AttachApplicationToDatabaseResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
