get:
  summary: 'List linked logical databases'
  operationId: listApplicationLogicalDatabase
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Application Database
  responses:
    '200':
      description: 'List linked databases'
      content:
        application/json:
          schema:
            $ref: '../schemas/LogicalDatabaseResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'