get:
  summary: 'Export environment variable'
  description: Return environment variables values in .env format
  operationId: exportEnvironmentVariable
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    -  Application Environment Variable 
  responses:
    '200':
      description: 'Get environment variable data'
      content:
        application/json:
          schema:
            type: object
            properties:
              values:
                type: string
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
