post:
  summary: 'Add application dependency to this application.'
  description: 'Add application dependency to this application to prevent this application starting before the linked dependencies'
  operationId: createApplicationDependency
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/path/targetApplicationId.yaml'
  tags:
    - Dependency
  responses:
    '200':
      description: 'Add application dependencies'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
      
delete:
  summary: 'Remove application dependency to this application.'
  operationId: removeApplicationDependency
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/path/targetApplicationId.yaml'
  tags:
    - Dependency
  responses:
    '204':
      $ref: '../responses/Deleted.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
