get:
  summary: 'Get current number of running instances of the application'
  operationId: getApplicationCurrentScale
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - application
  responses:
    '200':
      description: 'Know number of running instances of the application'
      content:
        application/json:
          schema:
            type: object
            properties:
              min:
                type: integer
              max:
                type: integer
              running:
                type: integer
              running_in_percent:
                type: number
              warning_threshold_in_percent:
                type: number
              alert_threshold_in_percent:
                type: number
              status:
                type: string
                enum:
                  - OK
                  - Warning
                  - Alert
              updated_at:
                type: string
                readOnly: true
                format: date-time
    '401':
      $ref: '../responses/NotAuthorized.yaml'