get:
  summary: 'List logs'
  operationId: listApplicationLog
  description: This will list the last 1000 logs of the application
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Application Logs
  responses:
    '200':
      description: 'List logs'
      content:
        application/json:
          schema:
            $ref: '../schemas/LogResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
