post:
  summary: 'Cancel application deployment'
  description: Cancel the current deployment of your application.
  operationId: cancelApplicationDeployment
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Application Actions
  responses:
    '202':
      description: 'Application deployment cancelling has been requested'
      content:
        application/json:
          schema:
            $ref: '../schemas/Status.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
    '409':
      description: 'Application deployment is already cancelled or an operation is in progress'
