get:
  summary: 'Get Custom Domain status'
  operationId: getCustomDomainStatus
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/path/customDomainId.yaml'
  tags:
    - Custom Domain
  responses:
    '200':
      description: 'Get status'
      content:
        application/json:
          schema:
            $ref: '../schemas/CustomDomainResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'