get:
  summary: 'List current storage disk usage'
  operationId: getApplicationCurrentStorageDisk
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Application Metrics
  responses:
    '200':
      description: 'Know current storage disk'
      content:
        application/json:
          schema:
            $ref: '../schemas/StorageDiskResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'