get:
  summary: 'Get Storage consumption metric over time for the application'
  operationId: getApplicationMetricStorage
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/query/lastSeconds.yaml'
  tags:
    - Application Metrics
  responses:
    '200':
      description: 'Storage consumption'
      content:
        application/json:
          schema:
            $ref: '../schemas/MetricStorageResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
