get:
  summary: 'List events'
  operationId: listApplicationEvent
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - application
  responses:
    '200':
      description: 'List events'
      content:
        application/json:
          schema:
            $ref: '../schemas/EventResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
