get:
  summary: 'List application restarts'
  description: 'Get application restart message and timestamp.'
  operationId: getApplicationMetricRestart
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/query/lastSeconds.yaml'
  tags:
    - Application Metrics
  responses:
    '200':
      description: 'Restarts'
      content:
        application/json:
          schema:
            $ref: '../schemas/MetricRestartResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
