post:
  summary: 'Add an alias on a built in environment variable of the application'
  description: |
    Create an alias on an environment application that was built in by Qovery
  operationId: createApplicationEnvironmentVariableAlias
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/path/environmentVariableId.yaml'
  tags:
    - application
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/EnvironmentVariableAlias.yaml'
  responses:
    '201':
      description: 'Added alias on environment variable'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentVariableResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'

delete:
  summary: 'Delete the alias on the environment variable belonging to the app'
  description: |
    
  operationId: deleteApplicationEnvironmentVariableAlias
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/path/environmentVariableId.yaml'
  tags:
    - application
  responses:
    '204':
      $ref: '../responses/NoContent.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
