post:
  summary: 'Abort application'
  operationId: abortApplication
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - application
  responses:
    '200':
      description: 'Application abort has been requested'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
    '409':
      description: 'Application is not building or deploying at the moment, or an operation is in progress'
