get:
  summary: 'List all the last application logs after a certain log Id'
  description: Returns all last logs that happened on the application, after the log ID you specify in the lastId query parameter. Response is not paginated
  operationId: listApplicationLogLastId
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/query/lastId.yaml'
  tags:
    - Application Logs
  responses:
    '200':
      description: 'List logs'
      content:
        application/json:
          schema:
            $ref: '../schemas/LogResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
