post:
  summary: 'Create a secret override at the application level'
  description: |
    - Allows you to override at application level a secret that has a higher scope.
    - You only have to specify a value in the request body
    - The system will create a new secret at application level with the same key as the one corresponding to the secret id in the path
    - The response body will contain the newly created secret
    - Information regarding the overriden_secret will be exposed in the "overriden_secret" field of the newly created secret
  operationId: createApplicationSecretOverride
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/path/secretId.yaml'
  tags:
    - Application Secret
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/Value.yaml'
  responses:
    '201':
      description: 'Create secret override'
      content:
        application/json:
          schema:
            $ref: '../schemas/SecretResponse.yaml'
    '400':
      description: Can't create an override on a higher scope. Overrides can only be created from one scope to a lower scope. Scope hierarchy is BUILT_IN > PROJECT > ENVIRONMENT > APPLICATION
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
