get:
  summary: 'List tags'
  operationId: listApplicationTag
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Application Main Calls
  responses:
    '200':
      description: 'List application tags'
      content:
        application/json:
          schema:
            $ref: '../schemas/TagResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'


post:
  summary: 'Add application tag'
  operationId: createApplicationTag
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Application Main Calls
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/TagRequest.yaml'
  responses:
    '201':
      description: 'Create application'
      content:
        application/json:
          schema:
            $ref: '../schemas/TagResponseList.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
