get:
  summary: 'List application dependencies'
  operationId: listApplicationDependency
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Dependency
  responses:
    '200':
      description: 'List dependencies'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
