get:
  summary: 'Get instant metrics of the application'
  operationId: getApplicationInstantMetrics
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - application
  responses:
    '200':
      description: 'Know current resource consumption of the application'
      content:
        application/json:
          schema:
            allOf:
              - $ref: '../schemas/InstanceResponseList.yaml'
              - type: object
                properties:
                  instance:
                    type: object
                    properties:
                      min: integer
                      max: integer
                      running: integer
                      running_in_percent: float
                      warning_threshold_in_percent: float
                      alert_threshold_in_percent: float
                      status:
                        type: string
                        enum:
                          - OK
                          - Warning
                          - Error
    '401':
      $ref: '../responses/NotAuthorized.yaml'