post:
  summary: 'add annotations group to application'
  description: 'add annotations group to application'
  operationId: addAnnotationsGroupToApplication
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/path/annotationsGroupId.yaml'
  tags:
    - Application Annotations Group
  responses:
    '204':
      $ref: '../responses/NoContent.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
delete:
  summary: 'delete annotations group to application'
  description: 'delete annotations group to application'
  operationId: deleteAnnotationsGroupToApplication
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/path/annotationsGroupId.yaml'
  tags:
    - Application Annotations Group
  responses:
    '204':
      $ref: '../responses/NoContent.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'