get:
  summary: 'Get current scaling of the application'
  description: Returns min, max, and running number of instances of the application
  operationId: getApplicationCurrentScale
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Application Metrics
  responses:
    '200':
      description: 'Get current scaling of the application'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationCurrentScaleResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'