get:
  summary: 'List currently running instances of the application with their resource metrics'
  operationId: getApplicationCurrentInstance
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Application Metrics
  responses:
    '200':
      description: 'Know current resource consumption of the application for each running instance'
      content:
        application/json:
          schema:
            $ref: '../schemas/InstanceResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'