post:
  summary: 'Link a logical database to the application'
  operationId: attachLogicalDatabasetoApplication
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/path/targetLogicalDatabaseId.yaml'
  tags:
    - Application Database
  responses:
    '201':
      description: 'Linked the Logical database to the application'
      content:
        application/json:
          schema:
            $ref: '../schemas/LogicalDatabaseResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
    '409':
      description: This logical database is already linked to the application
      
delete:
  summary: 'Remove logical database link to this application.'
  operationId: removeLogicalDatabaseFromApplication
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/path/targetLogicalDatabaseId.yaml'
  tags:
    - Application Database
  responses:
    '204':
      $ref: '../responses/NoContent.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
