delete:
  summary: 'Delete an environment variable from an application'
  description: 'To delete an environment variable from an application you must have the project user permission'
  operationId: deleteApplicationEnvironmentVariable
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/path/environmentVariableId.yaml'
  tags:
    - application
  responses:
    '204':
      $ref: '../responses/Deleted.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'