get:
  summary: 'List secrets'
  operationId: listApplicationSecrets
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - application
  responses:
    '200':
      description: 'List secrets'
      content:
        application/json:
          schema:
            $ref: '../schemas/SecretResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
post:
  summary: 'Add a secret'
  description: |
    Add a secret to the application. If the secret name does already exists, then it will be replaced by the new one.
  operationId: createApplicationSecret
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - application
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/SecretRequest.yaml'
  responses:
    '201':
      description: 'Add a secret'
      content:
        application/json:
          schema:
            $ref: '../schemas/SecretResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
