get:
  summary: 'List application annotations group'
  description: 'List application annotations group'
  operationId: listApplicationAnnotationsGroup
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Application Annotations Group
  responses:
    '200':
      description: 'List application annotations groups'
      content:
        application/json:
          schema:
            $ref: '../schemas/OrganizationAnnotationsGroupResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
