get:
  summary: 'Get Storage consumption metric over time for the application'
  operationId: getApplicationMetricStorage
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/query/lastSeconds.yaml'
  tags:
    - application
  responses:
    '200':
      description: 'Storage consumption'
      content:
        application/json:
          schema:
            type: object
            properties:
              results:
                type: array
                items:
                  $ref: '../schemas/MetricStorageResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
