get:
  summary: 'List application secrets'
  description: Secrets are like environment variables, but they are secured and can't be revealed.
  operationId: listApplicationSecrets
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - application
  responses:
    '200':
      description: 'List secrets'
      content:
        application/json:
          schema:
            $ref: '../schemas/SecretResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
post:
  summary: 'Add a secret to the application'
  description: |
    - Add a secret to the application.
      - If the secret key already exists, then it will be replaced by the new one.
      - If the secret value points toward an existing secret key, it will be considered as an alias.
  operationId: createApplicationSecret
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - application
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/SecretRequest.yaml'
  responses:
    '201':
      description: 'Add a secret'
      content:
        application/json:
          schema:
            $ref: '../schemas/SecretResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
