get:
  summary: 'List application deploys'
  description: By default it returns the 20 last results. The response is paginated. In order to request the next page, you can use the startId query parameter. You can also filter by status (FAILED or SUCCESS), and git_commit_id
  operationId: listApplicationDeploymentHistory
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/query/startId.yaml'

  tags:
    - Application Deployment History
  responses:
    '200':
      description: 'List deployment history'
      content:
        application/json:
          schema:
            $ref: '../schemas/DeploymentHistoryPaginatedResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'

