post:
  summary: 'Link a git repository to the application.'
  description: Allows to link a git repository to an existing application. If a git repository was already linked, then it will be replaced by the new one
  operationId: linkApplicationToGitRepository
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - application
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/ApplicationGitRepositoryRequest.yaml'
            
  responses:
    '201':
      description: 'Link git repository'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
