post:
  summary: 'Stop application'
  operationId: stopApplication
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Application Actions
  responses:
    '202':
      description: 'Application stop has been requested'
      content:
        application/json:
          schema:
            $ref: '../schemas/Status.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
    '409':
      description: 'Application is already stopped or an operation is in progress'
