get:
  summary: 'List contributors'
  operationId: listApplicationContributor
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - application
  responses:
    '200':
      description: 'List application contributors'
      content:
        application/json:
          schema:
            $ref: '../schemas/UserResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
