get:
  summary: 'List XX last application events'
  description: Returns all last XX events. Response is not paginated
  operationId: listApplicationEventTail
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/query/tail.yaml'
  tags:
    - Application Event
  responses:
    '200':
      description: 'List events'
      content:
        application/json:
          schema:
            $ref: '../schemas/EventResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
