get:
  summary: 'Get CPU consumption metric over time for the application'
  operationId: getApplicationMetricCpu
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/query/lastSeconds.yaml'

  tags:
    - Application Metrics
  responses:
    '200':
      description: 'CPU consumption'
      content:
        application/json:
          schema:
            type: object
            properties:
              results:
                type: array
                items:
                  $ref: '../schemas/MetricCPUResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
