get:
  summary: 'Get application status'
  operationId: getApplicationStatus
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Application Main Calls
  responses:
    '200':
      description: 'Get status'
      content:
        application/json:
          schema:
            $ref: '../schemas/Status.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
