get:
  summary: 'List XX last application logs'
  description: Returns all last XX application logs. Response is not paginated
  operationId: listApplicationLogTail
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/query/tail.yaml'
  tags:
    - application
  responses:
    '200':
      description: 'List logs'
      content:
        application/json:
          schema:
            $ref: '../schemas/LogResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
