get:
  summary: 'List commits'
  description: By default it returns the 20 last results. The response is paginated. In order to request the next page, you can use the startId query parameter. You can also filter by  git_commit_id

  operationId: listApplicationCommit
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/query/startId.yaml'
    - $ref: '../parameters/query/gitCommitId.yaml'

  tags:
    - application
  responses:
    '200':
      description: 'List commits'
      content:
        application/json:
          schema:
            $ref: '../schemas/CommitPaginatedResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
