post:
  summary: 'Add an override on an existing environment variable belonging to the application'
  description: |
    Override an environment application that would have been inherited by the application from a parent level (environment, project)
  operationId: createApplicationEnvironmentVariableOverride
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/path/environmentVariableId.yaml'
  tags:
    - application
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/EnvironmentVariableOverride.yaml'
  responses:
    '201':
      description: 'Added override on environment variable'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentVariableResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'

delete:
  summary: 'Delete the override on the environment variable belonging to the app'
  description: |
    
  operationId: deleteApplicationEnvironmentVariableOverride
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/path/environmentVariableId.yaml'
  tags:
    - application
  responses:
    '204':
      $ref: '../responses/NoContent.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
