post:
  summary: 'Rollback application from a given event'
  description: 'Rollback your application to a specific event that occured on your application'
  operationId: rollbackApplicationFromEvent
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/path/eventId.yaml'
  tags:
    - application
  responses:
    '202':
      description: 'Application rollbacked'
      content:
        application/json:
          schema:
            $ref: '../schemas/EventResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'