put:
  summary: 'Edit an application deployment restriction'
  description: 'Edit an application deployment restriction'
  operationId: editApplicationDeploymentRestriction
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/path/deploymentRestrictionId.yaml'

  tags:
    - Application Deployment Restriction
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/ApplicationDeploymentRestrictionRequest.yaml'
  responses:
    '200':
      description: 'Edit an application deployment restriction'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationDeploymentRestrictionResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'

delete:
  summary: 'Delete an application deployment restriction'
  description: 'Delete an application deployment restriction'
  operationId: deleteApplicationDeploymentRestriction
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
    - $ref: '../parameters/path/deploymentRestrictionId.yaml'
  tags:
    - Application Deployment Restriction
  responses:
    '204':
      $ref: '../responses/Deleted.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'