get:
  summary: 'Get application deployment rule'
  operationId: getApplicationDeploymentRule
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Application Deployment Rule
  responses:
    '200':
      description: 'Get deployment rule'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationDeploymentRuleResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'