get:
  summary: 'List container deployments'
  description: Returns the 20 last container deployments
  operationId: listContainerDeploymentHistory
  parameters:
    - $ref: '../parameters/path/containerId.yaml'
  tags:
    - Container Deployment History
  responses:
    '200':
      description: 'List deployment history'
      content:
        application/json:
          schema:
            $ref: '../schemas/DeploymentHistoryContainerPaginatedResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
