get:
  summary: 'List environment variables'
  operationId: listContainerEnvironmentVariable
  parameters:
    - $ref: '../parameters/path/applicationId.yaml'
  tags:
    - Container Environment Variable
  responses:
    '200':
      description: 'List environment variables'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentVariableResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
post:
  summary: 'Add an environment variable to the container'
  description: |
    - Add an environment variable to the container.
  operationId: createContainerEnvironmentVariable
  parameters:
    - $ref: '../parameters/path/containerId.yaml'

  tags:
    - Container Environment Variable
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/EnvironmentVariableRequest.yaml'
  responses:
    '201':
      description: 'Added an environment variable'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentVariableResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
