get:
  summary: 'List linked applications'
  operationId: listDatabaseApplication
  parameters:
    - $ref: '../parameters/path/databaseId.yaml'
  tags:
    - database
  responses:
    '200':
      description: 'List linked applications'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'