get:
  summary: 'List applications using the database'
  operationId: listDatabaseApplication
  parameters:
    - $ref: '../parameters/path/databaseId.yaml'
  tags:
    - database
  responses:
    '200':
      description: 'List linked applications'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'