get:
  summary: 'List applications using the database service'
  operationId: listDatabaseServiceApplication
  parameters:
    - $ref: '../parameters/path/databaseServiceId.yaml'
  tags:
    - databaseService
  responses:
    '200':
      description: 'List linked applications'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'