post:
  summary: 'Add an application to the database Service'
  operationId: attachApplicationToDatabaseService
  parameters:
    - $ref: '../parameters/path/databaseServiceId.yaml'
    - $ref: '../parameters/path/targetApplicationId.yaml'
  tags:
    - databaseService
  responses:
    '201':
      description: 'Added the application to the database Service'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '409':
      description: This application is already added on the database Service

      
delete:
  summary: 'Remove an application from this database Service'
  operationId: removeApplicationFromDatabaseService
  parameters:
    - $ref: '../parameters/path/databaseServiceId.yaml'
    - $ref: '../parameters/path/targetApplicationId.yaml'
  tags:
    - databaseService
  responses:
    '204':
      $ref: '../responses/NoContent.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
