delete:
  summary: 'Remove an application from this database '
  operationId: removeApplicationFromDatabase
  parameters:
    - $ref: '../parameters/path/databaseId.yaml'
    - $ref: '../parameters/path/targetApplicationId.yaml'
  tags:
    - Database Application
  responses:
    '204':
      $ref: '../responses/NoContent.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
