get:
  summary: 'List default cluster advanced settings'
  description: 'Default values for each setting is available in [our documentation](https://hub.qovery.com/docs/using-qovery/configuration/cluster-advanced-settings/)'
  operationId: getDefaultClusterAdvancedSettings
  tags:
    - Clusters
  responses:
    '200':
      description: 'Default cluster advanced settings'
      content:
        application/json:
          schema:
            $ref: '../schemas/ClusterAdvancedSettings.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
