get:
  summary: 'List default job advanced settings'
  description: 'Default values for each setting is available in [our documentation](https://hub.qovery.com/docs/using-qovery/configuration/advanced-settings/)'
  operationId: getDefaultJobAdvancedSettings
  tags:
    - Jobs
  responses:
    '200':
      description: 'Default job advanced settings'
      content:
        application/json:
          schema:
            $ref: '../schemas/job/JobAdvancedSettings.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
