get:
  summary: 'List default application advanced settings'
  operationId: getDefaultApplicationAdvancedSettings
  description: 'Default values for each setting is available in [our documentation](https://hub.qovery.com/docs/using-qovery/configuration/advanced-settings/)'
  tags:
    - Applications
  responses:
    '200':
      description: 'Default application advanced settings'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationAdvancedSettings.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
