get:
  summary: 'List default container advanced settings'
  description: 'Default values for each setting are available in [our documentation](https://hub.qovery.com/docs/using-qovery/configuration/advanced-settings/)'
  operationId: getDefaultContainerAdvancedSettings
  tags:
    - Containers
  responses:
    '200':
      description: 'Default container advanced settings'
      content:
        application/json:
          schema:
            $ref: '../schemas/ContainerAdvancedSettings.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
