get:
  summary: 'Export full environment and its resources into Terraform manifests'
  operationId: exportEnvironmentConfigurationIntoTerraform
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
    - $ref: '../parameters/query/exportSecrets.yaml'
  tags:
    - Applications
  responses:
    '200':
      description: 'Export full environment and its resources into Terraform manifests'
      content:
        application/zip:
          schema:
            type: string
            format: binary
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
