get:
  summary: 'List applications'
  operationId: listApplication
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - application
  responses:
    '200':
      description: 'List applications'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
post:
  summary: 'Create an application'
  operationId: createApplication
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - application
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/ApplicationRequest.yaml'
  responses:
    '200':
      description: 'Create application'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '409':
      description: Application name within the environment is already taken
