get:
  summary: 'List environment services'
  description: List all services within the environment (applications, databases, jobs, gateways...)
  operationId: listEnvironmentService
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - environment
  responses:
    '200':
      description: 'List environment services'
      content:
        application/json:
          schema:
            $ref: '../schemas/ServiceResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
