get:
  summary: 'List environment deployment logs'
  operationId: listEnvironmentLog
  description: By default it returns the 20 last results. The response is paginated. In order to request the next page, you can use the startId query parameter
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
    - $ref: '../parameters/query/startId.yaml'
  tags:
    - Environment Logs
  responses:
    '200':
      description: 'List logs'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentLogPaginatedResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
