get:
  summary: 'List all the last environment deploys after a certain event Id'
  description: Returns all last deploys that happened on the environment, after the event ID you specify in the lastId query parameter. Response is not paginated
  operationId: listEnvironmentDeploymentHistoryLastId
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
    - $ref: '../parameters/query/lastId.yaml'
  tags:
    - Environment Deployment History
  responses:
    '200':
      description: 'List deploys'
      content:
        application/json:
          schema:
            $ref: '../schemas/DeploymentHistoryResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
