get:
  summary: 'List environment deploys'
  description: By default it returns the 20 last results. The response is paginated. In order to request the next page, you can use the startId query parameter
  operationId: listEnvironmentDeploymentHistory
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
    - $ref: '../parameters/query/startId.yaml'
  tags:
    - environment
  responses:
    '200':
      description: 'List deployment history'
      content:
        application/json:
          schema:
            $ref: '../schemas/DeploymentHistoryPaginatedResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'

