get:
  summary: 'List all URLs of the environment'
  description: This will return you all the different URLs of all the applications within this environment
  operationId: listEnvironmentLinks
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - environment
  responses:
    '200':
      description: 'List links'
      content:
        application/json:
          schema:
            $ref: '../schemas/LinkResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
