post:
  summary: 'Create an environment variable alias at the environment level'
  description: |
    - Allows you to add an alias at environment level on an existing environment variable having higher scope, in order to customize its key.
    - You only have to specify a key in the request body
    - The system will create a new environment variable at environment level with the same value as the one corresponding to the variable id in the path
    - The response body will contain the newly created variable
    - Information regarding the aliased_variable will be exposed in the "aliased_variable" field of the newly created variable
    - You can't create an alias on an alias
  operationId: createEnvironmentEnvironmentVariableAlias
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
    - $ref: '../parameters/path/environmentVariableId.yaml'

  tags:
    - Environment Variable
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/Key.yaml'
  responses:
    '201':
      description: 'Create variable alias'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentVariableResponse.yaml'
    '400':
      description: Can't create an alias on a higher scope. Aliases can only be created from one scope to a lower scope. Scope hierarchy is BUILT_IN > PROJECT > ENVIRONMENT > APPLICATION
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'

