post:
  summary: 'Clone environment'
  description: You must provide a name. This will create a new environment, with the same configuration, and same applications and databases. Database data is not cloned.
  operationId: cloneEnvironment
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - environment
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/Name.yaml'
  responses:
    '202':
      description: 'Environment clone has been requested'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
    '409':
      description: 'Operation is in progress'
