delete:
  summary: 'Delete a secret from the environment'
  description: |
    - To delete a secret you must have the project user permission
    - You can't delete a BUILT_IN secret
    - If you delete a secret having override or alias, the associated override/alias will be deleted as well  operationId: deleteEnvironmentSecret
  operationId: deleteEnvironmentSecret
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
    - $ref: '../parameters/path/secretId.yaml'

  tags:
    - Environment Secret
  responses:
    '204':
      $ref: '../responses/Deleted.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'

put:
  summary: 'Edit a secret belonging to the environment'
  description: |
    - You can't edit a BUILT_IN secret
    - For an override, you can't edit the key
    - For an alias, you can't edit the value
    - An override can only have a scope lower to the secret it is overriding (hierarchy is BUILT_IN > PROJECT > ENVIRONMENT > APPLICATION)
  operationId: editEnvironmentSecret
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
    - $ref: '../parameters/path/secretId.yaml'

  tags:
    - Environment Secret
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/SecretEditRequest.yaml'

  responses:
    '200':
      description: 'Edited the secret value'
      content:
        application/json:
          schema:
            $ref: '../schemas/SecretResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
