get:
  summary: 'List current metric consumption for each database'
  operationId: listEnvironmentDatabaseCurrentMetric
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - Databases
  responses:
    '200':
      description: 'List current metric for each database'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentDatabasesCurrentMetricResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'



    