post:
  summary: 'Clone environment'
  operationId: cloneEnvironment
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - environment
  responses:
    '200':
      description: 'Environment clone has been requested'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '409':
      description: 'Operation is in progress'
