post:
  summary: 'Restart environment'
  operationId: restartEnvironment
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - environment
  responses:
    '200':
      description: 'Environment restart has been requested'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '409':
      description: An operation is in progress
