get:
  summary: 'Get all environment databases statuses'
  description: Returns a list of databases with only their id and status.
  operationId: getEnvironmentDatabaseStatus
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - database
  responses:
    '200':
      description: 'Get status'
      content:
        application/json:
          schema:
            allOf:
              - $ref: '../schemas/ReferenceObject.yaml'
              - $ref: '../schemas/Status.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'