post:
  summary: 'Create a secret alias at the environment level'
  description: |
    - Allows you to add an alias on an existing secret, at environment level, in order to customize its key.
    - You only have to specify a key in the request body
    - The system will create a new secret at environment level with the same value as the one corresponding to the secret id in the path
    - The response body will contain the newly created secret
    - Information regarding the aliased_secret will be exposed in the "aliased_secret" field of the newly created secret
    - Only 1 alias level is allowed. You can't create an alias on an alias
  operationId: createEnvironmentSecretAlias
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
    - $ref: '../parameters/path/secretId.yaml'
  tags:
    - environment
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/Key.yaml'
  responses:
    '201':
      description: 'Create secret alias'
      content:
        application/json:
          schema:
            $ref: '../schemas/SecretResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'

