get:
  summary: 'List environment databases'
  operationId: listDatabase
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - Databases
  responses:
    '200':
      description: 'List databases'
      content:
        application/json:
          schema:
            $ref: '../schemas/DatabaseResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
post:
  summary: 'Create a database'
  operationId: createDatabase
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - Databases
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/DatabaseRequest.yaml'
  responses:
    '201':
      description: 'Create database '
      content:
        application/json:
          schema:
            $ref: '../schemas/DatabaseResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
    '409':
      description: Database name within the environment is already taken
