delete:
  summary: 'Delete a secret from the environment'
  description: 'To delete a secret from the environment you must have the project user permission'
  operationId: deleteEnvironmentSecret
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
    - $ref: '../parameters/path/secretId.yaml'
  tags:
    - environment
  responses:
    '204':
      $ref: '../responses/Deleted.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'

put:
  summary: 'Change value of a secret belonging to the environment'
  operationId: editEnvironmentSecret
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
    - $ref: '../parameters/path/secretId.yaml'
  tags:
    - environment
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            value:
              type: string
  responses:
    '200':
      description: 'Edited the secret value'
      content:
        application/json:
          schema:
            $ref: '../schemas/SecretResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'