post:
  summary: 'Deploy containers'
  description: Deploy to the last commit the containers you specified. 
  operationId: deployAllContainers
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - Containers
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/DeployAllRequest.yaml'
  responses:
    '202':
      description: 'Deployed containers'
      content:
        application/json:
          schema:
            $ref: '../schemas/Status.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
    '409':
      description: 'Operation is in progress'
