get:
  summary: 'List all environment container statuses'
  description: Returns a list of containers with only their id and status.
  operationId: getEnvironmentContainerStatus
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - Containers
  responses:
    '200':
      description: 'Get status'
      content:
        application/json:
          schema:
            $ref: '../schemas/ReferenceObjectStatusResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'