post:
  summary: 'Restart services pods'
  description: |
    Restart pods of selected services.  
    Not available for managed databases.
  operationId: rebootServices
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - Environment Actions
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/RebootServicesRequest.yaml'
  responses:
    '202':
      description: 'Restart services pods has been requested'
      content:
        application/json:
          schema:
            $ref: '../schemas/Status.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
    '409':
      description: 'Operation is in progress'
