get:
  summary: 'List elligible database types, versions and modes for the environment'
  operationId: listEnvironmentDatabaseConfig
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - Environment Main Calls
  responses:
    '200':
      description: 'List elligible database'
      content:
        application/json:
          schema:
            $ref: '../schemas/DatabaseConfigurationResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'