get:
  summary: 'List applications to update'
  operationId: listApplicationToUpdate
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - Environment Main Calls
  responses:
    '200':
      description: 'List applications'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'