get:
  summary: 'List running instances with CPU and RAM usage for each container'
  operationId: getEnvironmentContainerCurrentInstance
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - Containers
  responses:
    '200':
      description: 'Know current resource consumption for each container of the environment'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentContainersInstanceResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
