get:
  summary: 'List applications'
  operationId: listApplication
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - Application Main Calls
  responses:
    '200':
      description: 'List applications'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
post:
  summary: 'Create an application'
  operationId: createApplication
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - Application Main Calls
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/ApplicationRequest.yaml'
  responses:
    '201':
      description: 'Create application'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
    '409':
      description: Application name within the environment is already taken
