post:
  summary: 'Deploy environment'
  description: This will deploy all the services of this environment to their latest version.
  operationId: deployEnvironment
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - environment
  responses:
    '202':
      description: 'Deploy environment'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
    '409':
      description: 'Operation is in progress'
