get:
  summary: 'List environment deployment logs'
  operationId: listEnvironmentLog
  description: This returns the last 1000 environment deployment logs.
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - Environment Logs
  responses:
    '200':
      description: 'List logs'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentLogResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
