get:
  summary: 'List environment deployments'
  description: List previous and current environment deployments with the status deployment and the related services. By default it returns the 20 last results. The response is paginated. In order to request the next page, you can use the startId query parameter
  operationId: listEnvironmentDeploymentHistory
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
    - $ref: '../parameters/query/startId.yaml'
  tags:
    - Environment Deployment History
  responses:
    '200':
      description: 'List deployment history'
      content:
        application/json:
          schema:
            $ref: '../schemas/DeploymentHistoryEnvironmentPaginatedResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'

