get:
  summary: 'List running instances with CPU and RAM usage for each application'
  operationId: getEnvironmentApplicationCurrentInstance
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - Applications
  responses:
    '200':
      description: 'Know current resource consumption for each application of the environment'
      content:
        application/json:
          schema:
            type: object
            properties:
              results:
                type: array
                items:
                  $ref: '../schemas/EnvironmentApplicationsInstanceResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
