get:
  summary: 'List supported languages'
  description: Returns list of languages supported by Buildpacks. 
  operationId: getEnvironmentApplicationSupportedLanguages
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - Applications
  responses:
    '200':
      description: 'Supported languages list.'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentApplicationsSupportedLanguageResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
