get:
  summary: 'Get environment variable by ID'
  operationId: getEnvironmentVariable
  parameters:
    - $ref: '../parameters/path/environmentVariableId.yaml'
  tags:
    - environmentVariable
  responses:
    '200':
      description: 'Get environment variable by ID'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentVariableResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'