post:
  summary: 'Cancel environment deployment'
  description: Cancel the current deployment of your environment.
  operationId: cancelEnvironmentDeployment
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - Environment Actions
  responses:
    '202':
      description: 'environment deployment cancelling has been requested'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentStatus.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
    '409':
      description: 'Environment deployment is already cancelled or an operation is in progress'
