post:
  summary: 'Create an environment variable alias at the environment level'
  description: |
    - Allows you to add an alias on an existing environment variable, at environment level, in order to customize its key.
    - You only have to specify a key in the request body
    - The system will create a new environment variable at environment level with the same value as the one corresponding to the variable id in the path
    - Information regarding the aliased_variable will be exposed in the "aliased_variable" field of the newly created variable
    - Only 1 alias level is allowed. You can't create an alias on an alias
  operationId: createEnvironmentEnvironmentVariableAlias
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
    - $ref: '../parameters/path/environmentVariableId.yaml'
  tags:
    - environment
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/Key.yaml'
  responses:
    '201':
      description: 'Create variable alias'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentVariableResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'

