get:
  summary: 'Get environment variable by ID'
  operationId: getEnvironmentVariable
  parameters:
    - $ref: '../parameters/path/environmentVariableId.yaml'
  tags:
    - environmentVariable
  responses:
    '200':
      description: 'Get environment variable by ID'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentVariableResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
put:
  summary: 'Edit an environment variable'
  description: 'To edit an environment variable you must have the project user permission'
  operationId: editEnvironmentVariable
  parameters:
    - $ref: '../parameters/path/environmentVariableId.yaml'
  tags:
    - environmentVariable
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/EnvironmentVariableRequest.yaml'
  responses:
    '200':
      description: 'Edit an environment variable'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentVariableResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
    '409':
      description: Environment variable name is already taken
delete:
  summary: 'Delete an environment variable'
  description: 'To delete an environment variable you must have the project user permission'
  operationId: deleteEnvironmentVariable
  parameters:
    - $ref: '../parameters/path/environmentVariableId.yaml'
  tags:
    - environmentVariable
  responses:
    '204':
      $ref: '../responses/Deleted.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
