get:
  summary: 'List environment database services'
  operationId: listDatabaseService
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - databaseService
  responses:
    '200':
      description: 'List database services'
      content:
        application/json:
          schema:
            $ref: '../schemas/DatabaseServiceResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
post:
  summary: 'Create a database service'
  operationId: createDatabaseService
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - databaseService
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/DatabaseServiceRequest.yaml'
  responses:
    '201':
      description: 'Create database service'
      content:
        application/json:
          schema:
            $ref: '../schemas/DatabaseServiceResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '409':
      description: Database Service name within the environment is already taken
