get:
  summary: 'List containers'
  operationId: listContainer
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
    - $ref: '../parameters/query/toUpdate.yaml'
  tags:
    - Containers
  responses:
    '200':
      description: 'List containers'
      content:
        application/json:
          schema:
            $ref: '../schemas/ContainerResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
post:
  summary: 'Create a container'
  operationId: createContainer
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - Containers
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/ContainerRequest.yaml'
  responses:
    '201':
      description: 'Create container'
      content:
        application/json:
          schema:
            $ref: '../schemas/ContainerResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
    '409':
      description: Container name within the environment is already taken
