post:
  summary: 'Deploy applications'
  description: 'Start a deployment of all the services within the chosen environment based on the following rule: a service ir deployed only if a new version is specified in the payload for that application/container or if there was a change in its configuration that needs to be applied (vCPU,RAM etc..)'
  operationId: deployAllApplications
  parameters:
    - $ref: '../parameters/path/environmentId.yaml'
  tags:
    - Environment
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/DeployAllRequest.yaml'
  responses:
    '202':
      description: 'Deployed applications'
      content:
        application/json:
          schema:
            $ref: '../schemas/Status.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
    '409':
      description: 'Operation is in progress'
