get:
  summary: 'List linked applications'
  operationId: listLogicalDatabaseApplication
  parameters:
    - $ref: '../parameters/path/logicalDatabaseId.yaml'
  tags:
    - logicalDatabase
  responses:
    '200':
      description: 'List linked applications'
      content:
        application/json:
          schema:
            $ref: '../schemas/ApplicationResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'