get:
  summary: 'Get cluster kubeconfig'
  operationId: getClusterKubeconfig
  parameters:
    - $ref: '../parameters/path/organizationId.yaml'
    - $ref: '../parameters/path/clusterId.yaml'
  tags:
    - Clusters
  responses:
    '200':
      description: 'Get kubeconfig of the cluster'
      content:
        application/x-yaml:
          schema:
            type: string
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
put:
  summary: 'Edit cluster kubeconfig'
  operationId: editClusterKubeconfig
  parameters:
    - $ref: '../parameters/path/organizationId.yaml'
    - $ref: '../parameters/path/clusterId.yaml'
  tags:
    - Clusters
  requestBody:
    content:
      application/x-yaml:
        schema:
          type: string
  responses:
    '204':
      description: 'edit kubeconfig of the cluster'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
