get:
  summary: 'List total number of services for each environment of the project'
  description: Returns a list of environment ids, and for each its total numberof services
  operationId: getProjectEnvironmentServiceNumber
  parameters:
    - $ref: '../parameters/path/projectId.yaml'
  tags:
    - Environments
  responses:
    '200':
      description: 'Get number of services'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentStatsResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'