get:
  summary: 'List project environment variables'
  operationId: listProjectEnvironmentVariable
  parameters:
    - $ref: '../parameters/path/projectId.yaml'
  tags:
    - Project Environment Variable
  responses:
    '200':
      description: 'List project environment variables'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentVariableResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'

post:
  summary: 'Add an environment variable to the project'
  description: |
    - Add an environment variable to the project.
      - If the environment variable key already exists, then it will be replaced by the new one.
      - If the environment variable value points toward an existing environment variable key, it will be considered as an alias.
  operationId: createProjectEnvironmentVariable
  parameters:
    - $ref: '../parameters/path/projectId.yaml'
    - $ref: '../parameters/query/dryRun.yaml'

  tags:
    - Project Environment Variable
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/EnvironmentVariableRequest.yaml'
  responses:
    '201':
      description: 'Added an environment variable'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentVariableResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
