get:
  summary: 'Get project deployment rule'
  operationId: getProjectDeploymentRule
  parameters:
    - $ref: '../parameters/path/projectId.yaml'
    - $ref: '../parameters/path/deploymentRuleId.yaml'
  tags:
    - Project Deployment Rule
  responses:
    '200':
      description: 'Get deployment rule'
      content:
        application/json:
          schema:
            $ref: '../schemas/ProjectDeploymentRuleResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'

put:
  summary: 'Edit a project deployment rule'
  operationId: editProjectDeployemtnRule
  parameters:
    - $ref: '../parameters/path/projectId.yaml'
    - $ref: '../parameters/path/deploymentRuleId.yaml'

  tags:
    - Project Deployment Rule
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/ProjectDeploymentRuleRequest.yaml'
  responses:
    '200':
      description: 'Edit a project deployment rule'
      content:
        application/json:
          schema:
            $ref: '../schemas/ProjectDeploymentRuleResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
    '409':
      description: Project name within the organization is already taken
delete:
  summary: 'Delete a project deployment rule'
  operationId: deleteProjectDeploymentRule
  parameters:
    - $ref: '../parameters/path/projectId.yaml'
    - $ref: '../parameters/path/deploymentRuleId.yaml'

  tags:
    - Project Deployment Rule
  responses:
    '204':
      $ref: '../responses/Deleted.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
