get:
  summary: 'List project deployment rules'
  operationId: listProjectDeploymentRule
  parameters:
    - $ref: '../parameters/path/projectId.yaml'
  tags:
    - project
  responses:
    '200':
      description: 'Get deployment rules'
      content:
        application/json:
          schema:
            $ref: '../schemas/ProjectDeploymentRuleResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'

post:
  summary: 'Create a deployment rule'
  operationId: createDeploymentRule
  parameters:
    - $ref: '../parameters/path/projectId.yaml'
  tags:
    - project
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/ProjectDeploymentRuleRequest.yaml'
  responses:
    '201':
      description: 'Create deployment rule'
      content:
        application/json:
          schema:
            $ref: '../schemas/ProjectDeploymentRuleResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
