get:
  summary: 'List environments statuses'
  description: Returns a list of environments with only their id and status.
  operationId: getProjectEnvironmentsStatus
  parameters:
    - $ref: '../parameters/path/projectId.yaml'
  tags:
    - Environments
  responses:
    '200':
      description: 'Get status'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentStatusList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
