get:
  summary: 'List environments'
  operationId: listEnvironment
  parameters:
    - $ref: '../parameters/path/projectId.yaml'
  tags:
    - Environments
  responses:
    '200':
      description: 'List environments'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentResponseList.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
post:
  summary: 'Create an environment'
  operationId: createEnvironment
  parameters:
    - $ref: '../parameters/path/projectId.yaml'
  tags:
    - Environments
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/CreateEnvironmentRequest.yaml'
  responses:
    '201':
      description: 'Create environment'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
    '409':
      description: Environment name within the project is already taken
