delete:
  summary: 'Delete an environment variable from a project'
  description: 'To delete an environment variable from a project you must have the project user permission'
  operationId: deleteProjectEnvironmentVariable
  parameters:
    - $ref: '../parameters/path/projectId.yaml'
    - $ref: '../parameters/path/environmentVariableId.yaml'
  tags:
    - project
  responses:
    '204':
      $ref: '../responses/Deleted.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'

put:
  summary: 'Change value of an environment variable belonging to the project'
  operationId: editProjectEnvironmentVariable
  parameters:
    - $ref: '../parameters/path/projectId.yaml'
    - $ref: '../parameters/path/environmentVariableId.yaml'
  tags:
    - project
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            value:
              type: string
  responses:
    '200':
      description: 'Edited the environment variable value'
      content:
        application/json:
          schema:
            $ref: '../schemas/EnvironmentVariableResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'