get:
  summary: 'Get project by ID'
  operationId: getProject
  parameters:
    - $ref: '../parameters/path/projectId.yaml'
  tags:
    - Project Main Calls
  responses:
    '200':
      description: 'Get project by ID'
      content:
        application/json:
          schema:
            $ref: '../schemas/ProjectResponse.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
put:
  summary: 'Edit a project'
  description: 'To edit a project you must have the admin permission'
  operationId: editProject
  parameters:
    - $ref: '../parameters/path/projectId.yaml'
  tags:
    - Project Main Calls
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../schemas/ProjectRequest.yaml'
  responses:
    '200':
      description: 'Edit a project'
      content:
        application/json:
          schema:
            $ref: '../schemas/ProjectResponse.yaml'
    '400':
      $ref: '../responses/BadRequest.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
    '409':
      description: Project name within the organization is already taken
delete:
  summary: 'Delete a project'
  description: 'To delete a project you must have the admin permission'
  operationId: deleteProject
  parameters:
    - $ref: '../parameters/path/projectId.yaml'
  tags:
    - Project Main Calls
  responses:
    '204':
      $ref: '../responses/Deleted.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'
