delete:
  summary: 'Delete an environment variable from a project'
  description: 'To delete an environment variable from a project you must have the project user permission'
  operationId: deleteProjectEnvironmentVariable
  parameters:
    - $ref: '../parameters/path/projectId.yaml'
    - $ref: '../parameters/path/environmentVariableId.yaml'
  tags:
    - project
  responses:
    '204':
      $ref: '../responses/Deleted.yaml'
    '401':
      $ref: '../responses/NotAuthorized.yaml'
    '403':
      $ref: '../responses/Forbidden.yaml'
    '404':
      $ref: '../responses/NotFound.yaml'