changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 💥 Breaking Changes
      labels:
        - breaking-change
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
        - docs
        - feat
    - title: 🧰 Bug fixes
      labels:
        - bug
        - fix
    - title: Other Changes
      labels:
        - '*'
