openapi: 3.0.0
info:
  version: 1.0.0
  title: Qovery API
servers:
  - url: 'https://api.qovery.com'
paths:
  /organization:
    get:
      summary: 'List user organizations'
      operationId: listOrganization
      tags:
        - organization
      responses:
        '200':
          description: 'List organizations'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationResponseList'
        '401':
          $ref: '#/components/responses/401'
    post:
      summary: 'Create an organization'
      operationId: createOrganization
      tags:
        - organization
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#'
      responses:
        '200':
          description: 'Create organization'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationResponse'
        '401':
          $ref: '#/components/responses/401'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    BaseResponse:
      type: object
      required:
        - id
        - created_at
      properties:
        id:
          type: string
          readOnly: true
        created_at:
          type: string
          readOnly: true
          format: date-time
    OrganizationRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        website_url:
          type: string
          nullable: true
    OrganizationResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          required:
            - name
          properties:
            name:
              type: string
            updated_at:
              type: string
              nullable: true
              format: date-time
    OrganizationResponseList:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/OrganizationResponse'
    UnexpectedError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
  responses:
    401:
      description: Access token is missing or invalid
security:
  - bearerAuth: [ ]
