openapi: 3.0.0
info:
  version: 1.0.0
  title: Qovery API
servers:
  - url: 'https://api.qovery.com'
paths:
  /organization:
    get:
      summary: 'List current user organizations quwyruoaaawdad toto tata'
      operationId: listOrganization
      tags:
        - organization
      responses:
        '200':
          description: 'List organizations'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Organization:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        created_at:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
