openapi: 3.0.0
info:
  version: 1.0.0
  title: Qovery API
servers:
  - url: 'https://api.qovery.com'
paths:
  /organization:
    get:
      summary: 'List user organizations'
      operationId: listOrganization
      tags:
        - organization
      responses:
        '200':
          description: 'List organizations'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationResponseList'
        '401':
          $ref: '#/components/responses/401'
    post:
      summary: 'Create an organization'
      operationId: createOrganization
      tags:
        - organization
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationRequest'
      responses:
        '200':
          description: 'Create organization'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationResponse'
        '401':
          $ref: '#/components/responses/401'
        '409':
          description: Organization name is already taken
  /organization/{organizationId}:
    put:
      summary: 'Edit an organization'
      description: 'To edit an organization you must have the admin permission'
      operationId: editOrganization
      parameters:
        - name: organizationId
          in: path
          description: Organization ID
          required: true
          schema:
            type: string
      tags:
        - organization
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationRequest'
      responses:
        '200':
          description: 'Edit an organization'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationResponse'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '409':
          description: Organization name is already taken
    delete:
      summary: 'Delete an organization'
      description: 'To delete an organization you must have the admin permission'
      operationId: deleteOrganization
      parameters:
        - name: organizationId
          in: path
          description: Organization ID
          required: true
          schema:
            type: string
      tags:
        - organization
      responses:
        '204':
          $ref: '#/components/responses/204-deletion'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '409':
          description: Organization name is already taken
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    BaseResponse:
      type: object
      required:
        - id
        - created_at
      properties:
        id:
          type: string
          readOnly: true
        created_at:
          type: string
          readOnly: true
          format: date-time
    OrganizationRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        website_url:
          type: string
          nullable: true
    OrganizationResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          required:
            - name
          properties:
            name:
              type: string
            updated_at:
              type: string
              nullable: true
              format: date-time
            logo_url:
              type: string
              format: uri
    OrganizationResponseList:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/OrganizationResponse'
    UnexpectedError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
  responses:
    204-deletion:
      description: The resource was deleted successfully
    401:
      description: Access token is missing or invalid
    403:
      description: Access forbidden
    404:
      description: Resource not found
    409:
      description: Conflict
security:
  - bearerAuth: [ ]
