type: object
required:
  - name
properties:
  name:
    type: string
    description: The name of the deployment stage
  description:
    type: string
    nullable: true
    description: free test describing this stage
