allOf:
  - $ref: '../BaseResponse.yaml'
  - type: object
    required:
      - environment
    properties:
      environment:
        $ref: '../ReferenceObject.yaml'
      name:
        type: string
        description: name is case insensitive
      description:
        type: string
      deployment_order:
        type: integer
        description: Position of the deployment stage within the environment
        example: 1
      services:
        $ref: './DeploymentStageServiceResponseList.yaml'
