allOf:
  - $ref: '../BaseResponse.yaml'
  - type: object
    properties:
      service_id:
        type: string
        format: uuid
        description: id of the service attached to the stage
      service_type:
        type: string
        description: type of the service (i.e APPLICATION, JOB, DATABASE, ...)
