type: object
properties:
  name:
    type: string
    required: true
    description: The name of the deployment stage
  description:
    type: string
    nullable: true
    description: free test describing this stage
