get:
  summary: 'List helms'
  operationId: listHelms
  parameters:
    - $ref: '../../parameters/path/environmentId.yaml'
    - $ref: '../../parameters/query/toUpdate.yaml'
  tags:
    - Helms
  responses:
    '200':
      description: 'List helms'
      content:
        application/json:
          schema:
            $ref: '../../schemas/helm/HelmResponseList.yaml'
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '404':
      $ref: '../../responses/NotFound.yaml'
post:
  summary: 'Create a helm'
  operationId: createHelm
  parameters:
    - $ref: '../../parameters/path/environmentId.yaml'
  tags:
    - Helms
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../schemas/helm/HelmRequest.yaml'
  responses:
    '201':
      description: 'Create helm'
      content:
        application/json:
          schema:
            $ref: '../../schemas/helm/HelmResponse.yaml'
    '400':
      $ref: '../../responses/BadRequest.yaml'
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '404':
      $ref: '../../responses/NotFound.yaml'
    '409':
      description: Helm name within the environment is already taken
