post:
  summary: 'Get helm default values'
  operationId: createHelmDefaultValues
  parameters:
    - $ref: '../../parameters/path/environmentId.yaml'
  tags:
    - Helms
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../schemas/helm/HelmDefaultValuesRequest.yaml'
  responses:
    '201':
      description: 'helm values'
      content:
        text/plain:
          schema:
            type: string
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '404':
      $ref: '../../responses/NotFound.yaml'
