post:
  summary: 'Import variables'
  description: Import environment variables in a defined scope, with a defined visibility.
  operationId: importHelmEnvironmentVariable
  parameters:
    - $ref: '../../parameters/path/helmId.yaml'
  tags:
    - Helm Environment Variable
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../schemas/VariableImportRequest.yaml'
  responses:
    '201':
      description: 'Import environment variables'
      content:
        application/json:
          schema:
            $ref: '../../schemas/VariableImportResponse.yaml'
    '400':
      $ref: '../../responses/BadRequest.yaml'
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '404':
      $ref: '../../responses/NotFound.yaml'
