get:
  summary: 'List last helm commits'
  description: Returns list of the last 100 commits made on the repository linked to helm
  operationId: listHelmCommit
  parameters:
    - $ref: '../../parameters/path/helmId.yaml'
    - $ref: '../../parameters/query/helmOf.yaml'
  tags:
    - Helm Main Calls
  responses:
    '200':
      description: 'List Helm commits'
      content:
        application/json:
          schema:
            $ref: '../../schemas/CommitResponseList.yaml'
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '404':
      $ref: '../../responses/NotFound.yaml'
