post:
  summary: 'Stop helm'
  operationId: stopHelm
  parameters:
    - $ref: '../../parameters/path/helmId.yaml'
  tags:
    - Helm Actions
  responses:
    '202':
      description: 'Helm stop has been requested'
      content:
        application/json:
          schema:
            $ref: '../../schemas/Status.yaml'
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '404':
      $ref: '../../responses/NotFound.yaml'
    '409':
      description: 'Helm is already stopped or an operation is in progress'
