get:
  summary: 'Get helm deployment restrictions'
  description: 'Get helm deployment restrictions'
  operationId: getHelmDeploymentRestrictions
  parameters:
    - $ref: '../../parameters/path/helmId.yaml'
  tags:
    - Helm Deployment Restriction
  responses:
    '200':
      description: 'Get helm deployment restrictions'
      content:
        application/json:
          schema:
            $ref: '../../schemas/helm/HelmDeploymentRestrictionResponseList.yaml'
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '404':
      $ref: '../../responses/NotFound.yaml'

post:
  summary: 'Create a helm deployment restriction'
  description: 'Create a helm deployment restriction'
  operationId: createHelmDeploymentRestriction
  parameters:
    - $ref: '../../parameters/path/helmId.yaml'
  tags:
    - Helm Deployment Restriction
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../schemas/helm/HelmDeploymentRestrictionRequest.yaml'
  responses:
    '201':
      description: 'Added an helm deployment restriction'
      content:
        application/json:
          schema:
            $ref: '../../schemas/helm/HelmDeploymentRestrictionResponse.yaml'
    '400':
      $ref: '../../responses/BadRequest.yaml'
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '409':
      description: A Helm deployment restriction with same properties already exists for this helm
