put:
  summary: 'Edit a helm deployment restriction'
  description: 'Edit a helm deployment restriction'
  operationId: editHelmDeploymentRestriction
  parameters:
    - $ref: '../../parameters/path/helmId.yaml'
    - $ref: '../../parameters/path/deploymentRestrictionId.yaml'

  tags:
    - Helm Deployment Restriction
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../schemas/helm/HelmDeploymentRestrictionRequest.yaml'
  responses:
    '200':
      description: 'Edit a helm deployment restriction'
      content:
        application/json:
          schema:
            $ref: '../../schemas/helm/HelmDeploymentRestrictionResponse.yaml'
    '400':
      $ref: '../../responses/BadRequest.yaml'
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '404':
      $ref: '../../responses/NotFound.yaml'

delete:
  summary: 'Delete a helm deployment restriction'
  description: 'Delete a helm deployment restriction'
  operationId: deleteHelmDeploymentRestriction
  parameters:
    - $ref: '../../parameters/path/helmId.yaml'
    - $ref: '../../parameters/path/deploymentRestrictionId.yaml'
  tags:
    - Helm Deployment Restriction
  responses:
    '204':
      $ref: '../../responses/Deleted.yaml'
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '404':
      $ref: '../../responses/NotFound.yaml'
