post:
  summary: 'Deprecated - Restart helm'
  description: '**Deprecated** - Please use the "Redeploy helm" endpoint now'
  operationId: restartHelm
  parameters:
    - $ref: '../../parameters/path/helmId.yaml'
    - name: forceEvent
      in: query
      required: false
      description: |
        When filled, it indicates the target event to be deployed.  
        If the concerned helm hasn't the target event provided, the helm won't be deployed.
      schema:
        $ref: ../../schemas/enums/HelmForceEvent.yaml
  tags:
    - Helm Actions
  responses:
    '202':
      description: 'Helm restart has been requested'
      content:
        application/json:
          schema:
            $ref: '../../schemas/Status.yaml'
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '404':
      $ref: '../../responses/NotFound.yaml'
    '409':
      description: 'Operation is in progress'
