get:
  summary: 'List helm deployments'
  description: Returns the 20 last helm deployments
  operationId: listHelmDeploymentHistory
  parameters:
    - $ref: '../../parameters/path/helmId.yaml'
  tags:
    - Helm Deployment History
  responses:
    '200':
      description: 'List deployment history'
      content:
        application/json:
          schema:
            $ref: '../../schemas/helm/DeploymentHistoryHelmPaginatedResponseList.yaml'
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '404':
      $ref: '../../responses/NotFound.yaml'
