type: object
properties:
  applications:
    type: object
    properties:
      items:
        type: object
        properties:
          id:
            type: string
            description: Set application ID
            format: uuid
