type: object
properties:
  sticky-session:
    type: boolean
    description: |
      Specify if the sticky session option (also called persistant session) is activated or not for this application.
      If activated, user will be redirected by the load balancer to the same instance each time he access to the application. 
    default: false