type: object
properties:
  environment:
    $ref: './ReferenceObject.yaml'
  git_repository:
    $ref: './ApplicationGitRepositoryResponse.yaml'
  maximum_cpu:
    type: number
    description: Maximum cpu that can be allocated to the application based on organization cluster configuration. unit is millicores (m). 1000m = 1 cpu
    default: 250
    example: 1250
  maximum_memory:
    type: number
    description: Maximum memory that can be allocated to the application based on organization cluster configuration. unit is MB. 1024 MB = 1GB
    default: 256
    example: 1024
  name:
    type: string
    description: name is case insensitive
  description:
    type: string
    description: give a description to this application
  build_mode:
    type: string
    enum:
      - DOCKER
      - BUILDPACKS
    default: BUILDPACKS
    description: |
      `DOCKER` requires `dockerfile_path`
      `BUILDPACKS` does not require any `dockerfile_path`
  dockerfile_path:
    type: string
    description: The path of the associated Dockerfile. Only if you are using build_mode = DOCKER
  buildpack_language:
    type: string
    description: Development langage of the application
    enum:
      - GO
      - NODE_JS
      - CLOJURE
      - PYTHON
      - JAVA
      - GRADLE
      - JVM
      - GRAILS
      - SCALA
      - PLAY 
      - PHP 
      - GO
  cpu:
    type: number
    description: unit is millicores (m). 1000m = 1 cpu
    default: 250
    example: 1250
  memory:
    type: number
    description: unit is MB. 1024 MB = 1GB
    default: 256
    example: 1024
  min_running_instances:
    type: integer
    minimum: 0
    description: |
      Minimum number of instances running. This resource auto-scale based on the CPU and Memory consumption.
      Note: 0 means that there is no application running.
    default: 1
  max_running_instances:
    type: integer
    maximum: -1
    description: |
      Maximum number of instances running. This resource auto-scale based on the CPU and Memory consumption.
      Note: -1 means that there is no limit.
    default: 1
  healthcheck:
    $ref: './Healthcheck.yaml'
  env_preview:
    type: boolean
    description: |
      Specify if the environment preview option is activated or not for this application.
      If activated, a preview environment will be automatically cloned at each pull request. 
    default: true
allOf:
  - $ref: './BaseResponse.yaml'
  - $ref: './ApplicationStorageResponse.yaml'
  - $ref: './ApplicationPortResponse.yaml'