type: object
properties:
  storage:
    type: array
    items:
      type: object
      required:
        - type
        - size
        - mount_point
      properties:
        type:
          type: string
          enum:
            - FAST_SSD
        size:
          type: integer
          description: unit is GB
          example: 16
        mount_point:
          type: string
          example: /mnt/images
