type: object
properties:
  deployment.delay_start_time_sec:
    type: integer
    default: 30
    deprecated: true
    description: please use `readiness_probe.initial_delay_seconds` and `liveness_probe.initial_delay_seconds` instead
  deployment.custom_domain_check_enabled:
    type: boolean
    description: disable custom domain check when deploying an application
    default: true
  deployment.termination_grace_period_seconds:
    type: integer
    description: define how long in seconds an application is supposed to be stopped gracefully
    default: 60
  build.timeout_max_sec:
    type: integer
    default: 1800
  network.ingress.proxy_body_size_mb:
    type: integer
    default: 100
  network.ingress.enable_cors:
    type: boolean
    default: false
  network.ingress.cors_allow_origin:
    type: string
    default: "*"
  network.ingress.cors_allow_methods:
    type: string
    default: GET, PUT, POST, DELETE, PATCH, OPTIONS
  network.ingress.cors_allow_headers:
    type: string
    default: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization
  network.ingress.proxy_buffer_size_kb:
    type: integer
    default: 4
    description: header buffer size used while reading response header from upstream
  network.ingress.keepalive_time_seconds:
    type: integer
    default: 3600
    description: Limits the maximum time (in seconds) during which requests can be processed through one keepalive connection
  network.ingress.keepalive_timeout_seconds:
    type: integer
    default: 60
    description: Sets a timeout (in seconds) during which an idle keepalive connection to an upstream server will stay open.
  network.ingress.send_timeout_seconds:
    type: integer
    default: 60
    description: Sets a timeout (in seconds) for transmitting a response to the client
  network.ingress.proxy_connect_timeout_seconds:
    type: integer
    default: 60
    description: Sets a timeout (in seconds) for establishing a connection to a proxied server
  network.ingress.proxy_send_timeout_seconds:
    type: integer
    default: 60
    description: Sets a timeout (in seconds) for transmitting a request to the proxied server
  network.ingress.proxy_read_timeout_seconds:
    type: integer
    default: 60
    description: Sets a timeout (in seconds) for reading a response from the proxied server
  network.ingress.whitelist_source_range:
    type: string
    description: |
      list of source ranges to allow access to ingress proxy. 
      This property can be used to whitelist source IP ranges for ingress proxy.
      The value is a comma separated list of CIDRs, e.g. 10.0.0.0/24,172.10.0.1
      To allow all source ranges, set 0.0.0.0/0.
    default: "0.0.0.0/0"
  network.ingress.denylist_source_range:
    type: string
    default: ""
    description: |
      list of source ranges to deny access to ingress proxy. 
      This property can be used to blacklist source IP ranges for ingress proxy.
      The value is a comma separated list of CIDRs, e.g. 10.0.0.0/24,172.10.0.1
  network.ingress.basic_auth_env_var:
    type: string
    default: ""
    description: |
      Set the name of an environment variable to use as a basic authentication (`login:crypted_password`) from `htpasswd` command.
  readiness_probe.type:
    type: string
    enum:
      - NONE
      - TCP
      - HTTP
    description: |
      `NONE` disable readiness probe
      `TCP` enable TCP readiness probe
      `HTTP` enable HTTP readiness probe
    default: TCP
  readiness_probe.http_get.path:
    type: string
    description: HTTP GET path to check status (must returns 2xx E.g "/healtz") - only usable with TYPE = HTTP
    default: /
  readiness_probe.initial_delay_seconds:
    type: integer
    description: Delay before liveness probe is initiated
    default: 30
  readiness_probe.period_seconds:
    type: integer
    description: How often to perform the probe
    default: 10
  readiness_probe.timeout_seconds:
    type: integer
    description: When the probe times out
    default: 1
  readiness_probe.success_threshold:
    type: integer
    description: Minimum consecutive successes for the probe to be considered successful after having failed.
    default: 1
  readiness_probe.failure_threshold:
    type: integer
    description: Minimum consecutive failures for the probe to be considered failed after having succeeded.
    default: 3
  liveness_probe.type:
    type: string
    enum:
      - NONE
      - TCP
      - HTTP
    description: |
      `NONE` disable liveness probe
      `TCP` enable TCP liveness probe
      `HTTP` enable HTTP liveness probe
    default: TCP
  liveness_probe.http_get.path:
    type: string
    description: HTTP GET path to check status (must returns 2xx E.g "/healtz") - only usable with TYPE = HTTP
    default: /
  liveness_probe.initial_delay_seconds:
    type: integer
    description: Delay before liveness probe is initiated
    default: 30
  liveness_probe.period_seconds:
    type: integer
    description: How often to perform the probe
    default: 10
  liveness_probe.timeout_seconds:
    type: integer
    description: When the probe times out
    default: 5
  liveness_probe.success_threshold:
    type: integer
    description: Minimum consecutive successes for the probe to be considered successful after having failed.
    default: 1
  liveness_probe.failure_threshold:
    type: integer
    description: Minimum consecutive failures for the probe to be considered failed after having succeeded.
    default: 3
  hpa.cpu.average_utilization_percent:
    type: integer
    description: Percentage value of cpu usage at which point pods should scale up.
    default: 60
