type: object
properties:
  has_access:
    type: boolean
  provider:
    type: string
    enum:
      - GITHUB
      - GITLAB
  owner:
    type: string
    example: John Doe
  name:
    type: string
    description: repository name
    example: simple-node-app
  deployed_commit_id:
    type: string
    description: Git commit ID corresponding to the deployed version of the app
  deployed_commit_date:
    type: string
    readOnly: true
    format: date-time
    description: Git commit date corresponding to the deployed version of the app
  deployed_commit_contributor:
    type: string
    format: uuid
    description: Git commit user corresponding to the deployed version of the app
  deployed_commit_tag:
    type: string
    example: "v1.0.1"