allOf:
  - $ref: './BaseResponse.yaml'
  - $ref: './ServiceStorageResponse.yaml'
  - type: object
    required:
      - healthchecks
      - name
      - environment
    properties:
      environment:
        $ref: './ReferenceObject.yaml'
      git_repository:
        $ref: './ApplicationGitRepositoryResponse.yaml'
      maximum_cpu:
        type: integer
        description: Maximum cpu that can be allocated to the application based on organization cluster configuration. unit is millicores (m). 1000m = 1 cpu
        example: 16000
      maximum_memory:
        type: integer
        description: Maximum memory that can be allocated to the application based on organization cluster configuration. unit is MB. 1024 MB = 1GB
        example: 16384
      name:
        type: string
        description: name is case insensitive
      description:
        type: string
        description: give a description to this application
      build_mode:
        $ref: './enums/BuildMode.yaml'
      dockerfile_path:
        type: string
        description: The path of the associated Dockerfile. Only if you are using build_mode = DOCKER
        nullable: true
      buildpack_language:
        $ref: "./enums/BuildPackLanguage.yaml"
      cpu:
        type: integer
        description: unit is millicores (m). 1000m = 1 cpu
        example: 1250
      memory:
        type: integer
        description: unit is MB. 1024 MB = 1GB
        example: 1024
      min_running_instances:
        type: integer
        minimum: 0
        description: |
          Minimum number of instances running. This resource auto-scale based on the CPU and Memory consumption.
          Note: 0 means that there is no application running.
        default: 1
      max_running_instances:
        type: integer
        description: |
          Maximum number of instances running. This resource auto-scale based on the CPU and Memory consumption.
          Note: -1 means that there is no limit.
        default: 1
      healthchecks:
        $ref: './Healthcheck.yaml'
      auto_preview:
        type: boolean
        description: |
          Specify if the environment preview option is activated or not for this application.  
          If activated, a preview environment will be automatically cloned at each pull request.  
          If not specified, it takes the value of the `auto_preview` property from the associated environment.
        default: true
      ports:
        $ref: './ServicePortResponseList.yaml'
      arguments:
        type: array
        items:
          type: string
      entrypoint:
        type: string
        description: optional entrypoint when launching container
      auto_deploy:
        type: boolean
        description: Specify if the application will be automatically updated after receiving a new commit.
