allOf:
  - $ref: './BaseResponse.yaml'
  - type: object
    properties:
      environment:
        $ref: './ReferenceObject.yaml'
      status:
        $ref: './Status.yaml'
  - $ref: './ApplicationRequest.yaml'
