allOf:
  - type: object
    properties:
      has_access:
        type: boolean
      deployed_commit_id:
        type: string
        description: Git commit ID corresponding to the deployed version of the app
      deployed_commit_date:
        type: string
        readOnly: true
        format: date-time
        description: Git commit date corresponding to the deployed version of the app
      deployed_commit_contributor:
        type: string
        format: uuid
        description: Git commit user corresponding to the deployed version of the app
  - $ref: './ApplicationGitRepositoryRequest.yaml'
