type: object
required:
  - settings
properties:
  settings:
    type: array
    items:
      type: object
      required:
        - name
        - value
      properties:
        name:
          type: string
        value:
          type: string
