type: object
properties:
  has_access:
    type: boolean
  provider:
    $ref: './enums/GitProvider.yaml'
  owner:
    type: string
    example: John Doe
  url:
    type: string
    format: uri
  name:
    type: string
    description: repository name
    example: simple-node-app
  branch:
    type: string
  root_path:
    type: string
  deployed_commit_id:
    type: string
    description: Git commit ID corresponding to the deployed version of the app
  deployed_commit_date:
    type: string
    readOnly: true
    format: date-time
    description: Git commit date corresponding to the deployed version of the app
  deployed_commit_contributor:
    type: string
    format: uuid
    description: Git commit user corresponding to the deployed version of the app
  deployed_commit_tag:
    type: string
    example: "v1.0.1"
  git_token_id:
    type: string
    format: uuid
    nullable: true
  git_token_name:
    type: string
    nullable: true
