type: object
properties:
  aws.cloudwatch.eks_logs_retention_days:
    type: integer
    default: 90
    description: Set the number of retention days for EKS Cloudwatch logs
  aws.vpc.enable_s3_flow_logs:
    type: boolean
    default: false
    description: Enable flow logs for on the VPC and store them in an S3 bucket
  aws.vpc.flow_logs_retention_days:
    type: integer
    default: 365
    description: Set the number of retention days for flow logs. Disable with value "0"
  database.postgresql.deny_public_access:
    type: boolean
    default: false
    description: Deny public access to any PostgreSQL database
  database.postgresql.allowed_cidrs:
    type: array
    default: ["0.0.0.0/0"]
    items:
      type: string
    description: List of CIDRs allowed to access the PostgreSQL database
  database.mysql.deny_public_access:
    type: boolean
    default: false
    description: Deny public access to any MySql database
  database.mysql.allowed_cidrs:
    type: array
    default: ["0.0.0.0/0"]
    items:
      type: string
    description: List of CIDRs allowed to access the MySql database
  database.mongodb.deny_public_access:
    type: boolean
    default: false
    description: Deny public access to any MongoDB/DocumentDB database
  database.mongodb.allowed_cidrs:
    type: array
    default: ["0.0.0.0/0"]
    items:
      type: string
    description: List of CIDRs allowed to access the MongoDB/DocumentDB database
  database.redis.deny_public_access:
    type: boolean
    default: false
    description: Deny public access to any Redis database
  database.redis.allowed_cidrs:
    type: array
    default: ["0.0.0.0/0"]
    items:
      type: string
    description: List of CIDRs allowed to access the Redis database
  registry.image_retention_time:
    type: integer
    default: 31536000
    description: Configure the number of seconds before cleaning images in the registry
  loki.log_retention_in_week:
    type: integer
    default: 12
    description: For how long in week loki is going to keep logs of your applications
  cloud_provider_container_registry_tags:
    type: object
    additionalProperties:
      type: string
    description: Add additional tags on the cluster dedicated registry
  load_balancer.size:
    type: string
    default: "lb-s"
    description: Select the size of the main load_balancer (only effective for Scaleway)
  pleco.resources_ttl:
    type: integer
    default: -1
    deprecated: true
  aws.iam.admin_group:
    type: string
    default: "Admins"
    description: AWS IAM group name with cluster access
