type: object
properties:
  aws.cloudwatch.eks_logs_retention_days:
    type: integer
    description: Set the number of retention days for EKS Cloudwatch logs
  aws.vpc.enable_s3_flow_logs:
    type: boolean
    description: Enable flow logs for on the VPC and store them in an S3 bucket
  aws.vpc.flow_logs_retention_days:
    type: integer
    description: Set the number of retention days for flow logs. Disable with value "0"
  loki.log_retention_in_week:
    type: integer
    description: For how long in week loki is going to keep logs of your applications
  registry.image_retention_time:
    type: integer
    description: Configure the number of seconds before cleaning images in the registry
  cloud_provider.container_registry.tags:
    type: object
    additionalProperties:
      type: string
    description: Add additional tags on the cluster dedicated registry
  load_balancer.size:
    type: string
    description: Select the size of the main load_balancer (only effective for Scaleway)
  database.postgresql.deny_public_access:
    type: boolean
    description: Deny public access to any PostgreSQL database
  database.postgresql.allowed_cidrs:
    type: array
    items:
      type: string
    description: List of CIDRs allowed to access the PostgreSQL database
  database.mysql.deny_public_access:
    type: boolean
    description: Deny public access to any MySql database
  database.mysql.allowed_cidrs:
    type: array
    items:
      type: string
    description: List of CIDRs allowed to access the MySql database
  database.mongodb.deny_public_access:
    type: boolean
    description: Deny public access to any MongoDB/DocumentDB database
  database.mongodb.allowed_cidrs:
    type: array
    items:
      type: string
    description: List of CIDRs allowed to access the MongoDB/DocumentDB database
  database.redis.deny_public_access:
    type: boolean
    description: Deny public access to any Redis database
  database.redis.allowed_cidrs:
    type: array
    items:
      type: string
    description: List of CIDRs allowed to access the Redis database
  aws.iam.admin_group:
    type: string
    description: AWS IAM group name with cluster access
  aws.eks.ec2.metadata_imds:
    type: string
    enum: ["optional", "required"]
    description: >
      Specify the [IMDS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) version you want to use:
        * `required`: IMDS V2 only
        * `optional`: IMDS V1 + V2
  pleco.resources_ttl:
    type: integer
    deprecated: true
  registry.mirroring_mode:
    $ref: './enums/RegistryMirroringMode.yaml'
  nginx.vcpu.request_in_milli_cpu:
    type: integer
    description: vcpu request in millicores
  nginx.vcpu.limit_in_milli_cpu:
    type: integer
    description: vcpu limit in millicores
  nginx.memory.request_in_mib:
    type: integer
    description: memory request in MiB
  nginx.memory.limit_in_mib:
    type: integer
    description: memory limit in MiB
  nginx.hpa.cpu_utilization_percentage_threshold:
    type: integer
    description: hpa cpu threshold in percentage
  nginx.hpa.min_number_instances:
    type: integer
    description: hpa minimum number of instances
  nginx.hpa.max_number_instances:
    type: integer
    description: hpa maximum number of instances
