type: object
properties:
  status:
    type: string
    enum:
      - SUCCESS
      - FAILED
  applications:
    type: array
    items:
      - $ref: './DeploymentHistoryApplicationResponse.yaml'
  databases:
      type: array
      items:
        - $ref: './DeploymentHistoryDatabaseResponse.yaml'
allOf:
  - $ref: './BaseResponse.yaml'
