type: object
required:
  - name
  - mode
  - cluster
  - start_time
  - stop_time
  - weekday
properties:
  name:
    type: string
    description: name is case insensitive
  description: 
    type: string
  mode:
    type: string
    enum:
      - PRODUCTION
      - DEVELOPMENT
  cluster:
    type: string
    format: uuid
  auto_deploy:
    type: boolean
    default: true
  auto_delete:
    type: boolean
    default: false
  start_time:
    type: string
    format: date-time
  stop_time:
    type: string
    format: date-time
  weekday:
    type: string
    enum: [MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY]
    example: [MONDAY, WEDNESDAY, FRIDAY]

