allOf:
  - $ref: './BaseResponse.yaml'
  - type: object
    properties:
      name:
        type: string
      commit:
        $ref: './CommitResponse.yaml'
      status:
        $ref: './enums/GlobalDeploymentStatus.yaml'
