allOf:
  - $ref: './BaseResponse.yaml'
  - type: object
    properties:
      commit:
        $ref: './CommitResponse.yaml'
      status:
        type: string
        enum:
          - SUCCESS
          - FAILED
