type: object
properties:
  status:
    type: string
    enum:
      - READY
      - BUILDING
      - BUILD_ERROR
      - BUILT
      - DEPLOYMENT_QUEUED
      - DEPLOYING
      - DEPLOYMENT_ERROR
      - DEPLOYED
      - STOP_QUEUED
      - STOPPING
      - STOP_ERROR
      - STOPPED
      - DELETE_QUEUED
      - DELETING
      - DELETE_ERROR
      - DELETED
      - RUNNING
      - RUNNING_ERROR
  applications:
    type: array
    items:
      $ref: './DeploymentHistoryApplicationResponse.yaml'
  databases:
    type: array
    items:
      $ref: './DeploymentHistoryDatabaseResponse.yaml'
allOf:
  - $ref: './BaseResponse.yaml'
