allOf:
  - $ref: './BaseResponse.yaml'
  - type: object
    properties:
      status:
        $ref: './enums/GlobalStatus.yaml'
      applications:
        type: array
        items:
          $ref: './DeploymentHistoryApplicationResponse.yaml'
      databases:
        type: array
        items:
          $ref: './DeploymentHistoryDatabaseResponse.yaml'
