allOf:
  - $ref: './BaseResponse.yaml'
  - type: object
    properties:
      name:
        type: string
        description: name of the service
      commit:
        $ref: './CommitResponse.yaml'
      status:
        $ref: './enums/DeploymentHistoryStatus.yaml'
