allOf:
  - $ref: './BaseResponse.yaml'
  - type: object
    properties:
      name:
        type: string
        description: name of the container
      status:
        $ref: './enums/State.yaml'
      image_name:
        type: string
      tag:
        type: string
      arguments:
        type: array
        items:
          type: string
      entrypoint:
        type: string
