allOf:
  - $ref: './BaseResponse.yaml'
  - type: object
    properties:
      status:
        $ref: './enums/State.yaml'
      origin:
        $ref: './enums/OrganizationEventOrigin.yaml'
      triggered_by:
        type: string
      applications:
        type: array
        items:
          $ref: './DeploymentHistoryApplicationResponse.yaml'
      containers:
        type: array
        items:
          $ref: './DeploymentHistoryContainerResponse.yaml'
      databases:
        type: array
        items:
          $ref: './DeploymentHistoryDatabaseResponse.yaml'
      jobs:
        type: array
        items:
          $ref: './job/DeploymentHistoryJobResponse.yaml'
