allOf:
  - $ref: './BaseResponse.yaml'
  - type: object
    required:
      - name
      - cloud_provider
      - mode
      - cluster_id
      - project
    properties:
      name:
        type: string
        description: name is case insensitive
      organization:
        $ref: './ReferenceObject.yaml'
      project:
        $ref: './ReferenceObject.yaml'
      last_updated_by:
        type: string
        format: uuid
        description: uuid of the user that made the last update
      cloud_provider:
        type: object
        properties:
          provider:
            type: string
            example: aws
          cluster:
            type: string
            example: us-east-2
      mode:
        $ref: './enums/EnvironmentMode.yaml'
      cluster_id:
        type: string
        format: uuid
      cluster_name:
        type: string
        format: string
