type: object
required:
  - key
  - value
properties:
  key:
    type: string
    description: key is case sensitive.
  value:
    type: string
    description: value of the env variable.
  mount_path:
    type: string
    nullable: true
    default: null
    description: should be set for file only. variable mount path makes variable a file (where file should be mounted).
