type: object
required:
  - name
  - cloud_provider
properties:
  name:
    type: string
    description: name is case insensitive
  cloud_provider:
    type: object
    properties:
      provider:
        type: string
        example: aws
      cluster:
        type: string
        example: us-east-2
  mode:
    type: string
    enum:
      - PRODUCTION
      - DEVELOPMENT
