type: object
required:
  - id
  - state
  - last_deployment_state
properties:
  id:
    type: string
    format: uuid
  state:
    $ref: './enums/State.yaml'
  last_deployment_date:
    type: string
    format: date-time
    nullable: true
  last_deployment_state:
    $ref: './enums/State.yaml'
  last_deployment_id:
    type: string
    nullable: true
  total_deployment_duration_in_seconds:
    type: integer
    nullable: true
