type: object
required:
  - id
  - key
  - value
  - mount_path
  - scope
  - type
properties:
  id:
    type: string
    format: uuid
  key:
    type: string
    example: QOVERY_DATABASE_PSQL_NAME
  value:
    type: string
  mount_path:
    type: string
  scope:
    $ref: './enums/APIVariableScope.yaml'
  type:
    $ref: './enums/APIVariableType.yaml'
