type: object
required:
  - id
  - state
  - last_deployment_state
properties:
  id:
    type: string
    format: uuid
  state:
    $ref: './enums/State.yaml'
  last_deployment_date:
    type: string
    format: date-time
  last_deployment_state:
    $ref: './enums/State.yaml'
  last_deployment_id:
    type: string
