type: object
properties:
  auto_deploy:
    type: boolean
    default: true
  always_up:
    type: boolean
    default: false
  start_time:
    type: string
    format: date-time
    nullable: true
    description: specify value only if always_up = false
  stop_time:
    type: string
    format: date-time
    nullable: true
    description: specify value only if always_up = false
  weekday:
    type: string
    enum: [MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY]
    example: MONDAY
    nullable: true
    description: specify value only if always_up = false