type: object
required:
  - application
  - instances
properties:
  application:
    type: string
    format: uuid
  instances:
    type: array
    items:
      $ref: '../schemas/InstanceResponse.yaml'