type: object
properties:
  auto_deploy:
    type: boolean
    default: true
  auto_stop:
    type: boolean
    default: false
  timezone:
    type: string
    nullable: false
    default: Europe/London
    description: specify value only if auto_stop = false
  start_time:
    type: string
    format: date-time
    nullable: true
    description: specify value only if auto_stop = false
  stop_time:
    type: string
    format: date-time
    nullable: true
    description: specify value only if auto_stop = false
  weekdays:
    type: array
    nullable: true
    description: specify value only if auto_stop = false
    items:
      type: string
      enum: [MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY]
      example: MONDAY
allOf:
  - $ref: './BaseResponse.yaml'
