type: object
required:
  - timezone
  - start_time
  - stop_time
  - weekdays
properties:
  auto_deploy:
    type: boolean
    default: true
  auto_stop:
    type: boolean
    default: false
  timezone:
    type: string
    example: UTC
  start_time:
    type: string
    format: date-time
    example: 1970-01-01T08:00:00Z
  stop_time:
    type: string
    format: date-time
    example: 1970-01-01T19:00:00Z
  weekdays:
    type: array
    items:
      type: string
      enum: [MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY]
      example: MONDAY
allOf:
  - $ref: './BaseResponse.yaml'
