type: object
properties:
  applications:
    type: array
    items:
      $ref: '../schemas/Status.yaml'
  containers:
    type: array
    items:
      $ref: '../schemas/Status.yaml'
  jobs:
    type: array
    items:
      $ref: '../schemas/Status.yaml'
  databases:
    type: array
    items:
      $ref: '../schemas/Status.yaml'
  stage:
    $ref: '../schemas/Stage.yaml'
