allOf:
  - $ref: './BaseResponse.yaml'
  - type: object
    properties:
      override:
        $ref: './EnvironmentVariableOverride.yaml'
      alias:
        $ref: './EnvironmentVariableAlias.yaml'
  - $ref: './EnvironmentVariableRequest.yaml'