type: object
properties:
  database:
    type: string
    format: uuid
  cpu:
    type: object
    properties:
      requested_in_float:
        type: number
      consumed_in_number:
        type: number
      consumed_in_percent:
        type: number
      warning_threshold_in_percent:
        type: number
      alert_threshold_in_percent:
        type: number
      status:
        $ref: './enums/ThresholdMetricStatus.yaml'
  memory:
    type: object
    properties:
      requested_in_mb:
        type: integer
      consumed_in_mb:
        type: integer
      consumed_in_percent:
        type: number
      warning_threshold_in_percent:
        type: number
      alert_threshold_in_percent:
        type: number
      status:
        $ref: './enums/ThresholdMetricStatus.yaml'
  storage:
    type: object
    properties:
      requested_in_gb:
        type: integer
      consumed_in_gb:
        type: integer
      consumed_in_percent:
        type: number
      warning_threshold_in_percent:
        type: number
      alert_threshold_in_percent:
        type: number
      status:
        $ref: './enums/ThresholdMetricStatus.yaml'