type: object
required:
  - id
  - key
  - value
  - mount_path
  - scope
  - variable_type
properties:
  id:
    type: string
    format: uuid
  key:
    type: string
  value:
    type: string
  mount_path:
    type: string
  scope:
    $ref: './enums/APIVariableScope.yaml'
  variable_type:
    $ref: './enums/APIVariableType.yaml'
