type: object
required:
  - name
properties:
  name:
    type: string
    description: name is case insensitive
  cluster_id:
    type: string
    format: uuid
  mode:
    type: string
    enum:
      - PRODUCTION
      - DEVELOPMENT
      - STAGING
      - PREVIEW
