type: object
required:
  - type
  - timestamp
  - details
properties:
  type:
    type: string
    format: string
  timestamp:
    type: string
    format: date-time
  details:
    type: object
    properties:
      organization_id:
        type: string
        format: uuid
      cluster_id:
        type: string
        format: uuid
      execution_id:
        type: string
      transmitter:
        type: object
        properties:
          id:
            type: string
            format: uuid
          name:
            type: string
          type:
            type: string
      stage:
        type: object
        properties:
          step:
            type: string
          id:
            type: string
            format: uuid
            nullable: true
          name:
            type: string
            nullable: true
  error:
    type: object
    nullable: true
    properties:
      tag:
        type: string
      user_log_message:
        type: string
      link:
        type: string
      hint_message:
        type: string
      underlying_error:
        type: object
        properties:
          message:
            type: string
          full_details:
            type: string
  message:
    type: object
    nullable: true
    properties:
      safe_message:
        type: string
      full_details:
        type: string
