type: object
properties:
  auto_deploy:
    type: boolean
    default: true
  always_up:
    type: boolean
    default: false
  timezone:
    type: string
    nullable: false
    default: Europe/London
    description: specify value only if always_up = false
  start_time:
    type: string
    format: date-time
    nullable: true
    description: specify value only if always_up = false
  stop_time:
    type: string
    format: date-time
    nullable: true
    description: specify value only if always_up = false
  weekdays:
    type: array
    nullable: true
    description: specify value only if always_up = false
    items:
      type: string
      enum: [MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY]
      example: MONDAY
