type: object
properties:
  results:
    type: array
    items:
      type: object
      required:
        - application
        - instances
      properties:
        application:
          type: string
          format: uuid
        instances:
          type: array
          items:
            $ref: '../schemas/InstanceResponse.yaml'