allOf:
  - $ref: './BaseResponse.yaml'
  - type: object
    properties:
      project:
        $ref: './ReferenceObject.yaml'
      status:
        $ref: './Status.yaml'
  - $ref: './EnvironmentRequest.yaml'
