allOf:
  - $ref: './BaseResponse.yaml'
  - type: object
    required:
      - name
      - cloud_provider
      - mode
      - cluster_id
    properties:
      name:
        type: string
        description: name is case insensitive
      project:
        $ref: './ReferenceObject.yaml'
      last_updated_by:
        type: string
        format: uuid
        description: uuid of the user that made the last update
      cluster:
        type: object
        properties:
          id:
            type: string
            format: uuid
          name:
            type: string
          provider:
            type: string
            example: aws
          region:
            type: string
            example: us-east-2
      mode:
        $ref: './enums/EnvironmentMode.yaml'
