type: object
required:
  - id
  - created_at
  - service
  - status
  - message
properties:
  id:
    type: string
    format: uuid
  created_at:
    type: string
    format: date-time
  scope:
    type: object
    properties:
      type:
        type: string
        enum:
          - APPLICATION
          - DATABASE
          - ENVIRONMENT
      name:
        type: string
      id:
        type: string
        format: uuid
  state:
    type: string
    description: |
      Status is a state machine. It starts with `BUILDING` or `DEPLOYING` state (or `INITIALIZED`if auto-deploy is deactivated). Then finish with `*_ERROR` or any termination state.
    enum:
      - BUILD_ERROR
      - BUILDING
      - BUILT
      - DELETE_ERROR
      - DELETED
      - DELETING
      - DEPLOYED
      - DEPLOYING
      - DEPLOYMENT_ERROR
      - INITIALIZED
      - QUEUED
      - RUNNING
      - RUNNING_ERROR
      - STOP_ERROR
      - STOPPED
      - STOPPING
  message:
    type: string
    nullable: true
    description: Log message
  execution_id:
    type: string
    description: Only for errors. Helps Qovery team to investigate.
  hint:
    type: string
    example: only for errors. it gives a possible action to the user -- Markdown can be injected
