type: object
required:
  - url
  - branch
  - paths
properties:
  url:
    type: string
    description: application git repository URL
    example: https://github.com/Qovery/simple-node-app
  branch:
    type: string
    description: |
      Name of the branch to use. This is optional
      If not specified, then the branch used is the `main` or `master` one
    example: feat/text_xxx
  paths:
    type: array
    description: List of path inside your git repository to locate values file. Must start by a /
    items:
      type: string
  git_token_id:
    type: string
    format: uuid
    description: The git token id on Qovery side
    nullable: true
