allOf:
  - $ref: './DeploymentRuleRequest.yaml'
  - type: object
    required:
      - environment_target
    properties:
      environment_target:
        type: string
        description: specify here a regex based on environment name that will target new environments after their creation
        example: ^feat