type: object
required:
  - name
  - mode
  - cluster_id
  - timezone
  - start_time
  - stop_time
  - weekdays
  - wildcard
properties:
  name:
    type: string
    description: name is case insensitive
    example: project-rule
  description:
    type: string
    nullable: true
    example: description project rule
  mode:
    type: string
    enum:
      - DEVELOPMENT
      - STAGING
      - PRODUCTION
  cluster_id:
    type: string
    format: uuid
  auto_deploy:
    type: boolean
    default: false
  auto_stop:
    type: boolean
    default: false
  auto_delete:
    type: boolean
    default: false
  timezone:
    type: string
    example: UTC
  start_time:
    type: string
    format: date-time
    example: 1970-01-01T08:00:00Z
  stop_time:
    type: string
    format: date-time
    example: 1970-01-01T19:00:00Z
  weekdays:
    type: array
    items:
      type: string
      enum: [MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY]
      example: MONDAY
  wildcard:
    type: string
    default: ""
    description: wildcard pattern composed of '?' and/or '*' used to target new created environments
