put:
  summary: 'Attach service to deployment stage'
  operationId: AttachServiceToDeploymentStage
  parameters:
    - $ref: '../../parameters/path/deploymentStageId.yaml'
    - $ref: '../../parameters/path/serviceId.yaml'
  tags:
    - Deployment Stage Main Calls
  responses:
    '200':
      description: 'List of deployment stages for the env'
      content:
        application/json:
          schema:
            $ref: '../../schemas/deploymentStage/DeploymentStageResponseList.yaml'
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '404':
      $ref: '../../responses/NotFound.yaml'
