put:
  summary: 'Move deployment stage before requested stage'
  operationId: MoveBeforeDeploymentStage
  parameters:
    - $ref: '../../parameters/path/deploymentStageId.yaml'
    - $ref: '../../parameters/path/stageId.yaml'
  tags:
    - Deployment Stage Main Calls
  responses:
    '200':
      description: 'List deployment stage'
      content:
        application/json:
          schema:
            $ref: '../../schemas/deploymentStage/DeploymentStageResponseList.yaml'
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '404':
      $ref: '../../responses/NotFound.yaml'
