get:
  summary: 'Get Service Deployment Stage'
  operationId: getServiceDeploymentStage
  parameters:
    - $ref: '../../parameters/path/serviceId.yaml'
  tags:
    - Deployment Stage Main Calls
  responses:
    '200':
      description: 'Get Service Deployment Stage'
      content:
        application/json:
          schema:
            $ref: '../../schemas/deploymentStage/DeploymentStageResponse.yaml'
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '404':
      $ref: '../../responses/NotFound.yaml'