get:
  summary: 'List all environment job statuses'
  description: Returns a list of jobs with only their id and status.
  operationId: getEnvironmentJobStatus
  parameters:
    - $ref: '../../parameters/path/environmentId.yaml'
  tags:
    - Jobs
  responses:
    '200':
      description: 'Get status'
      content:
        application/json:
          schema:
            $ref: '../../schemas/ReferenceObjectStatusResponseList.yaml'
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '404':
      $ref: '../../responses/NotFound.yaml'