get:
  summary: 'List job deployments'
  description: Returns the 20 last job deployments
  operationId: listJobDeploymentHistory
  parameters:
    - $ref: '../../parameters/path/jobId.yaml'
  tags:
    - Job Deployment History
  responses:
    '200':
      description: 'List deployment history'
      content:
        application/json:
          schema:
            $ref: '../../schemas/job/DeploymentHistoryJobPaginatedResponseList.yaml'
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '404':
      $ref: '../../responses/NotFound.yaml'
