put:
  summary: 'Edit a job deployment restriction'
  description: 'Edit a job deployment restriction'
  operationId: editJobDeploymentRestriction
  parameters:
    - $ref: '../../parameters/path/jobId.yaml'
    - $ref: '../../parameters/path/deploymentRestrictionId.yaml'

  tags:
    - Job Deployment Restriction
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../schemas/job/JobDeploymentRestrictionRequest.yaml'
  responses:
    '200':
      description: 'Edit a job deployment restriction'
      content:
        application/json:
          schema:
            $ref: '../../schemas/job/JobDeploymentRestrictionResponse.yaml'
    '400':
      $ref: '../../responses/BadRequest.yaml'
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '404':
      $ref: '../../responses/NotFound.yaml'

delete:
  summary: 'Delete a job deployment restriction'
  description: 'Delete a job deployment restriction'
  operationId: deleteJobDeploymentRestriction
  parameters:
    - $ref: '../../parameters/path/jobId.yaml'
    - $ref: '../../parameters/path/deploymentRestrictionId.yaml'
  tags:
    - Job Deployment Restriction
  responses:
    '204':
      $ref: '../../responses/Deleted.yaml'
    '401':
      $ref: '../../responses/NotAuthorized.yaml'
    '403':
      $ref: '../../responses/Forbidden.yaml'
    '404':
      $ref: '../../responses/NotFound.yaml'
