allOf:
  - type: object
    required:
      - source
    properties:
      source:
        oneOf:
          - type: object
            properties:
              git_repository:
                $ref: '../HelmGitRepositoryRequest.yaml'
          - type: object
            properties:
              helm_repository:
                type: object
                properties:
                  repository:
                    type: string
                    format: UUID
                    description: The id of the helm repository
                    nullable: true
                  chart_name:
                    type: string
                    description: The name of the chart in the repository
                  chart_version:
                    type: string
                    description: The version of the chart to use
