allOf:
  - $ref: '../BaseResponse.yaml'
  - type: object
    required:
      - environment
      - name
      - auto_preview
      - auto_deploy
      - source
      - values_override
      - arguments
      - allow_cluster_wide_resources
    properties:
      environment:
        $ref: '../ReferenceObject.yaml'
      name:
        type: string
        description: name is case insensitive
      description:
        type: string
      timeout_sec:
        type: integer
        minimum: 0
        default: 600
        description: |
          Maximum number of seconds allowed for helm to run before killing it and mark it as failed
      auto_preview:
        type: boolean
        description: |
          Indicates if the 'environment preview option' is enabled.  
          If enabled, a preview environment will be automatically cloned when `/preview` endpoint is called.  
          If not specified, it takes the value of the `auto_preview` property from the associated environment.
      auto_deploy:
        type: boolean
        description: |
          Specify if the service will be automatically updated after receiving a new image tag or a new commit according to the source type.
      ports:
        $ref: './HelmPortResponseList.yaml'
      source:
        nullable: false
        oneOf:
          - type: object
            properties:
              git:
                type: object
                properties:
                  git_repository:
                    $ref: '../ApplicationGitRepositoryRequest.yaml'
          - type: object
            properties:
              repository:
                type: object
                required:
                  - chart_name
                  - chart_version
                  - repository
                properties:
                  chart_name:
                    type: string
                    description: The name of the chart in the repository
                  chart_version:
                    type: string
                    description: The version of the chart to use
                  repository:
                    type: object
                    required:
                      - id
                      - name
                      - url
                    properties:
                      id:
                        type: string
                        format: UUID
                        description: The id of the helm repository
                      name:
                        type: string
                        description: The name of the helm repository
                      url:
                        type: string
                        description: The url the helm repository
      arguments:
        type: array
        description: The extra arguments to pass to helm
        items:
          type: string
      allow_cluster_wide_resources:
        type: boolean
        default: false
        description: |
          If we should allow the chart to deploy object outside his specified namespace.
          Setting this flag to true, requires special rights
      values_override:
        type: object
        description: |
          Specify helm values you want to set or override
        properties:
          set:
            type: array
            items:
              $ref: './HelmKeyValue.yaml'
          set_string:
            type: array
            items:
              $ref: './HelmKeyValue.yaml'
          set_json:
            type: array
            items:
              $ref: './HelmKeyValue.yaml'
          file:
            type: object
            nullable: true
            properties:
              raw:
                type: object
                nullable: true
                required:
                  - values
                properties:
                  values:
                    type: array
                    items:
                      type: object
                      required:
                        - name
                        - content
                      properties:
                        name:
                          type: string
                          description: The name of the value file
                        content:
                          type: string
                          description: The content of the value file
              git:
                type: object
                nullable: true
                required:
                  - git_repository
                  - paths
                properties:
                  git_repository:
                    $ref: '../ApplicationGitRepositoryRequest.yaml'
                  paths:
                    type: array
                    description: List of path inside your git repository to locate values file. Must start by a /
                    items:
                      type: string
