allOf:
  - $ref: '../BaseResponse.yaml'
  - type: object
    properties:
      name:
        type: string
        description: name of the job
      status:
        $ref: '../enums/DeploymentHistoryStatus.yaml'
      image_name:
        type: string
      tag:
        type: string
      arguments:
        type: array
        items:
          type: string
      entrypoint:
        type: string
