allOf:
  - $ref: '../BaseResponse.yaml'
  - type: object
    properties:
      name:
        type: string
        description: name of the job
      status:
        $ref: '../enums/State.yaml'
      image_name:
        type: string
      tag:
        type: string
      commit:
        $ref: '../CommitResponse.yaml'
      schedule:
        type: object
        properties:
          event:
            $ref: '../enums/JobScheduleEvent.yaml'
          schedule_at:
            type: string
            format: cron
            nullable: true
            description: |
              Can only be set if the event is CRON.
              Represent the cron format for the job schedule without seconds.
              For example: `* * * * *` represent the cron to launch the job every minute.
              See https://crontab.guru/ to WISIWIG interface.
              Timezone is UTC
      arguments:
        type: array
        items:
          type: string
      entrypoint:
        type: string
