type: object
properties:
  build.timeout_max_sec:
    type: integer
    description: define the max timeout for the build
  build.cpu_max_in_milli:
    type: integer
    description: define the max cpu resources (in milli)
  build.ram_max_in_gib:
    type: integer
    description: define the max ram resources (in gib)
  deployment.termination_grace_period_seconds:
    type: integer
    description: define how long in seconds an application is supposed to be stopped gracefully
  deployment.affinity.node.required:
    type: object
    additionalProperties:
      type: string
    description: Set pod placement on specific Kubernetes nodes labels
  job.delete_ttl_seconds_after_finished:
    type: integer
    nullable: true
  cronjob.concurrency_policy:
    type: string
  cronjob.failed_jobs_history_limit:
    type: integer
  cronjob.success_jobs_history_limit:
    type: integer
  security.service_account_name:
    type: string
    description: |
      Allows you to set an existing Kubernetes service account name
  security.automount_service_account_token:
    type: boolean
    description: |
      Automount Kubernetes service account token to have access to Kubernetes API from pods
  security.read_only_root_filesystem:
    type: boolean
    description: |
      Mounts the container's root filesystem as read-only
