name: generate-clients

on:
  push:
    branches: [main, chore-test-generator]

jobs:
  generate:
    runs-on: ubuntu-latest
    # if: success() && github.ref == 'refs/heads/main'

    strategy:
      matrix:
        include:
          - language: go
            target-branch: master
          - language: javascript
            target-branch: main
          - language: python
            target-branch: master
          - language: typescript
            target-branch: main

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Build OpenApi file
        run: |
          npm ci
          npm run build
      - name: Generate ${{ matrix.language }} client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: ${{ matrix.language }}
          generator-tag: v5.4.0
          openapi-file: _build/openapi.yaml
          command-args: |
            -a bearer \
            -o out/qovery-client-${{ matrix.language }} \
            --git-user-id qovery \
            --git-repo-id qovery-client-${{ matrix.language }} \
            --package-name qovery
      - name: Check post generation script existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'generator/post_generation_scripts/${{ matrix.language }}.sh'
      - name: Run ${{ matrix.language }} post generation script
        if: steps.check_files.outputs.files_exists == 'true'
        run: generator/post_generation_scripts/${{ matrix.language }}.sh
      - name: Publish ${{ matrix.language }} client
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: out/qovery-client-${{ matrix.language }}
          destination-github-username: 'qovery'
          destination-repository-name: 'qovery-client-${{ matrix.language }}'
          user-email: github@qovery.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: ${{ matrix.target-branch }}
