name: generate-clients

on:
  push:
    branches: [main, chore-test-generator]

jobs:
  generate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [go]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Build OpenApi file
        run: |
          npm ci
          npm run build
      - name: Generate ${{ matrix.language }} Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: ${{ matrix.language }}
          generator-tag: v5.4.0
          config-file: generator-config/${{ matrix.language }}.yml
          openapi-file: _build/openapi.yaml
          command-args: -o out/qovery-client-${{ matrix.language }} -a bearer --git-user-id qovery --git-repo-id qovery-client-${{ matrix.language }}
      - name: Publish ${{ matrix.language }} Client
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: out/qovery-client-${{ matrix.language }}
          destination-github-username: 'qovery'
          destination-repository-name: 'qovery-client-${{ matrix.language }}'
          user-email: github@qovery.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: master

  # go-client:
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-go@v2
  #       with:
  #         go-version: '1.17'
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.x'
  #     - name: Build OpenApi file
  #       run: |
  #         npm ci
  #         npm run build
  #     - name: Generate Go Client
  #       uses: openapi-generators/openapitools-generator-action@v1
  #       with:
  #         generator: go
  #         generator-tag: v5.4.0
  #         config-file: generator-config/go.yml
  #         openapi-file: _build/openapi.yaml
  #         command-args: $DEFAULT_COMMAND_ARGS --git-repo-id qovery-client-go
  #     - name: Fix generated code
  #       run: |
  #         sed -i 's/AnyOfstringboolean/interface{}/g' $(find out/client/ -type f)
  #         gofmt -s -w -l out/client/
  #     - name: Pushes to another repository
  #       id: push_directory
  #       uses: cpina/github-action-push-to-another-repository@main
  #       env:
  #         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  #       with:
  #         source-directory: out/client/
  #         destination-github-username: 'qovery'
  #         destination-repository-name: 'qovery-client-go'
  #         user-email: github@qovery.com
  #         commit-message: See ORIGIN_COMMIT from $GITHUB_REF
  #         target-branch: master
  # python-client:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Generate Python Client
  #       run: |
  #         npm ci
  #         QOVERY_CLIENT_LANGUAGE=python npm run generate
  #     - name: Pushes to another repository
  #       id: push_directory
  #       uses: cpina/github-action-push-to-another-repository@main
  #       env:
  #         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  #       with:
  #         source-directory: out/client/
  #         destination-github-username: 'qovery'
  #         destination-repository-name: 'qovery-client-python'
  #         user-email: github@qovery.com
  #         commit-message: See ORIGIN_COMMIT from $GITHUB_REF
  #         target-branch: master
  # typescript-client:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Generate Typescript Client
  #       run: |
  #         npm ci
  #         QOVERY_CLIENT_LANGUAGE=typescript npm run generate
  #     - name: Pushes to another repository
  #       id: push_directory
  #       uses: cpina/github-action-push-to-another-repository@main
  #       env:
  #         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  #       with:
  #         source-directory: out/client/
  #         destination-github-username: 'qovery'
  #         destination-repository-name: 'qovery-client-typescript'
  #         user-email: github@qovery.com
  #         commit-message: See ORIGIN_COMMIT from $GITHUB_REF
  #         target-branch: main
  # javascript-client:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Generate Javascript Client
  #       run: |
  #         npm ci
  #         QOVERY_CLIENT_LANGUAGE=javascript npm run generate
  #     - name: Pushes to another repository
  #       id: push_directory
  #       uses: cpina/github-action-push-to-another-repository@main
  #       env:
  #         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  #       with:
  #         source-directory: out/client/
  #         destination-github-username: 'qovery'
  #         destination-repository-name: 'qovery-client-javascript'
  #         user-email: github@qovery.com
  #         commit-message: See ORIGIN_COMMIT from $GITHUB_REF
  #         target-branch: main
