name: Run Spectral on Pull Requests

on:
  - pull_request

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stoplightio/spectral-action@v0.8.1
        with:
          file_glob: 'src/openapi.yaml'
          spectral_ruleset: '.spectral.yaml'
